package state

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"time"

	"github.com/crateos/crateos/internal/config"
	"github.com/crateos/crateos/internal/modules"
	"github.com/crateos/crateos/internal/platform"
	"github.com/crateos/crateos/internal/users"
)

// Action represents a single remediation step.
type Action struct {
	Description string `json:"description"`
	Component   string `json:"component"` // "directory", "service", "network", "symlink"
	Target      string `json:"target"`
}

func writeManagedActorOwnershipState(index managedActorOwnershipIndex) {
	snapshot := ActorOwnershipState{
		Claims: make([]ActorOwnershipStateItem, 0, len(index.Actors)),
	}
	for _, actor := range index.Actors {
		item := ActorOwnershipStateItem{
			Crate:     actor.Crate,
			Name:      actor.Name,
			Type:      actor.Type,
			ID:        actor.ID,
			User:      actor.User,
			Group:     actor.Group,
			Home:      actor.Home,
			UpdatedAt: actor.UpdatedAt,
			RetiredAt: actor.RetiredAt,
			Status:    "retired",
		}
		if actor.Active {
			item.Status = "claimed"
			snapshot.Active++
		} else {
			snapshot.Retired++
		}
		snapshot.Claims = append(snapshot.Claims, item)
	}
	writeActorOwnershipState(snapshot)
}

func writeManagedExecutionArtifacts(desired config.ServiceEntry, crate CrateState, hasMod bool) {
	if hasMod || crate.ExecutionAdapter != "systemd" || crate.PrimaryUnitPath == "" {
		return
	}
	serviceContent := renderManagedServiceUnit(desired, crate)
	if _, err := writeManagedArtifact(
		filepath.ToSlash(filepath.Join("services", desired.Name, "runtime", "rendered", "systemd", crate.PrimaryUnit)),
		crate.PrimaryUnitPath,
		serviceContent,
		"service",
		fmt.Sprintf("rendered managed execution unit %s", crate.PrimaryUnit),
	); err != nil {
		log.Printf("warning: render managed execution unit %s: %v", desired.Name, err)
	}
	if crate.ExecutionMode == "job" && crate.CompanionUnitPath != "" {
		timerContent := renderManagedTimerUnit(desired, crate)
		if _, err := writeManagedArtifact(
			filepath.ToSlash(filepath.Join("services", desired.Name, "runtime", "rendered", "systemd", crate.CompanionUnit)),
			crate.CompanionUnitPath,
			timerContent,
			"service",
			fmt.Sprintf("rendered managed timer unit %s", crate.CompanionUnit),
		); err != nil {
			log.Printf("warning: render managed timer unit %s: %v", desired.Name, err)
		}
	}
}

func renderManagedServiceUnit(desired config.ServiceEntry, crate CrateState) string {
	lines := []string{
		"# Generated by CrateOS.",
		"# Generated native service artifact managed by CrateOS.",
		"[Unit]",
		fmt.Sprintf("Description=CrateOS managed workload for %s", desired.Name),
		"After=network.target",
		"",
		"[Service]",
	}
	if crate.ExecutionMode == "job" {
		lines = append(lines, "Type=oneshot")
	} else {
		lines = append(lines, "Type=simple")
	}
	if crate.ActorUser != "" {
		// TODO: Provision and verify the managed actor account before native activation so User=/Group= never point at a missing identity.
		lines = append(lines, "User="+crate.ActorUser)
	}
	if crate.ActorGroup != "" {
		lines = append(lines, "Group="+crate.ActorGroup)
	}
	if crate.WorkingDir != "" {
		lines = append(lines, "WorkingDirectory="+crate.WorkingDir)
	}
	if crate.ActorRuntimeDir != "" {
		// TODO: Enforce actor runtime directory ownership during reconcile instead of relying on RuntimeDirectory defaults alone.
		lines = append(lines, "RuntimeDirectory="+filepath.Base(crate.ActorRuntimeDir))
		lines = append(lines, "RuntimeDirectoryPreserve=yes")
	}
	if crate.ActorStateDir != "" {
		// TODO: Create and chown actor state paths during apply so hosted workloads do not inherit root-owned state unexpectedly.
		lines = append(lines, "StateDirectory=crateos/"+desired.Name+"/"+filepath.Base(crate.ActorStateDir))
	}
	if crate.EnvironmentFile != "" {
		lines = append(lines, "EnvironmentFile=-"+crate.EnvironmentFile)
	}
	if crate.StartCommand != "" {
		lines = append(lines, "ExecStart=/bin/sh -lc "+quoteSystemdShell(crate.StartCommand))
	} else {
		lines = append(lines, "# ExecStart pending module binding or execution.start_cmd")
	}
	if crate.Timeout != "" && crate.Timeout != "0" {
		lines = append(lines, "RuntimeMaxSec="+crate.Timeout)
	}
	if crate.StopTimeout != "" {
		lines = append(lines, "TimeoutStopSec="+crate.StopTimeout)
	}
	if crate.KillSignal != "" {
		lines = append(lines, "KillSignal="+crate.KillSignal)
	}
	lines = append(lines,
		"# TODO: Add stronger systemd hardening once actor provisioning and ownership enforcement land end-to-end.",
		fmt.Sprintf("# Managed actor pending lifecycle provisioning: %s", valueOrDefault(crate.ActorName, "unassigned")),
		fmt.Sprintf("# Managed actor id: %s", valueOrDefault(crate.ActorID, "pending")),
		fmt.Sprintf("# Managed actor user/group: %s:%s", valueOrDefault(crate.ActorUser, "pending"), valueOrDefault(crate.ActorGroup, "pending")),
		fmt.Sprintf("# Managed actor home: %s", valueOrDefault(crate.ActorHome, "pending")),
		fmt.Sprintf("# Deploy source: %s", valueOrDefault(crate.DeploySource, "unspecified")),
		fmt.Sprintf("# Entry: %s", valueOrDefault(crate.Entry, "unspecified")),
		"",
		"[Install]",
		"WantedBy=multi-user.target",
		"",
	)
	return strings.Join(lines, "\n")
}

func renderManagedTimerUnit(desired config.ServiceEntry, crate CrateState) string {
	onCalendar := translateExecutionSchedule(crate.Schedule)
	lines := []string{
		"# Generated by CrateOS.",
		"# Generated native timer artifact managed by CrateOS.",
		"[Unit]",
		fmt.Sprintf("Description=CrateOS managed schedule for %s", desired.Name),
		"",
		"[Timer]",
		fmt.Sprintf("Unit=%s", crate.PrimaryUnit),
		"Persistent=true",
	}
	if onCalendar != "" {
		lines = append(lines, "OnCalendar="+onCalendar)
	} else {
		// TODO: Replace the narrow cron-like translation with a first-class CrateOS schedule model before exposing richer recurrence rules.
		lines = append(lines, "# OnCalendar translation failed; timer activation remains blocked.")
	}
	lines = append(lines,
		fmt.Sprintf("# Source schedule: %s", valueOrDefault(crate.Schedule, "unspecified")),
		"",
		"[Install]",
		"WantedBy=timers.target",
		"",
	)
	return strings.Join(lines, "\n")
}

func quoteSystemdShell(command string) string {
	command = strings.ReplaceAll(command, "\\", "\\\\")
	command = strings.ReplaceAll(command, "\"", "\\\"")
	return "\"" + command + "\""
}

func valueOrDefault(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func managedActorIDSeed(crateName, actorName string, ordinal int) string {
	base := strings.TrimSpace(actorName)
	if base == "" {
		base = strings.TrimSpace(crateName)
	}
	seed := fmt.Sprintf("%s|%s|%d", strings.TrimSpace(crateName), base, ordinal)
	sum := sha256.Sum256([]byte(seed))
	hexID := hex.EncodeToString(sum[:16])
	return fmt.Sprintf("%s-%s-%s-%s-%s", hexID[0:8], hexID[8:12], hexID[12:16], hexID[16:20], hexID[20:32])
}

func managedActorAccountName(actorID string, ordinal int) string {
	compact := strings.ReplaceAll(strings.TrimSpace(actorID), "-", "")
	if compact == "" {
		return ""
	}
	suffix := ""
	if ordinal > 0 {
		suffix = fmt.Sprintf("-%d", ordinal)
	}
	maxCompact := 32 - len("ca-") - len(suffix)
	if maxCompact > len(compact) {
		maxCompact = len(compact)
	}
	if maxCompact < 8 {
		maxCompact = 8
	}
	return "ca-" + compact[:maxCompact] + suffix
}

type managedActorRegistry struct {
	GeneratedAt string                   `json:"generated_at"`
	Actor       managedActorRegistryItem `json:"actor"`
}

type managedActorRegistryItem struct {
	Name      string `json:"name,omitempty"`
	Type      string `json:"type,omitempty"`
	ID        string `json:"id,omitempty"`
	User      string `json:"user,omitempty"`
	Group     string `json:"group,omitempty"`
	Home      string `json:"home,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}

type managedActorProvisioningState struct {
	GeneratedAt   string `json:"generated_at"`
	LastSuccessAt string `json:"last_success_at,omitempty"`
	LastFailureAt string `json:"last_failure_at,omitempty"`
	Events        []managedActorProvisioningEvent `json:"events,omitempty"`
	Actor         struct {
		Name      string `json:"name,omitempty"`
		Type      string `json:"type,omitempty"`
		ID        string `json:"id,omitempty"`
		User      string `json:"user,omitempty"`
		Group     string `json:"group,omitempty"`
		Home      string `json:"home,omitempty"`
		RuntimeDir string `json:"runtime_dir,omitempty"`
		StateDir  string `json:"state_dir,omitempty"`
	} `json:"actor"`
	Provisioning string `json:"provisioning,omitempty"`
	Error        string `json:"error,omitempty"`
}

type managedActorProvisioningEvent struct {
	At           string `json:"at"`
	Provisioning string `json:"provisioning,omitempty"`
	Error        string `json:"error,omitempty"`
}

type managedActorOwnershipIndex struct {
	GeneratedAt string                      `json:"generated_at"`
	Actors      []managedActorOwnershipItem `json:"actors,omitempty"`
}

type managedActorOwnershipItem struct {
	Crate     string `json:"crate"`
	Name      string `json:"name,omitempty"`
	Type      string `json:"type,omitempty"`
	ID        string `json:"id"`
	User      string `json:"user"`
	Group     string `json:"group,omitempty"`
	Home      string `json:"home,omitempty"`
	Active    bool   `json:"active"`
	UpdatedAt string `json:"updated_at,omitempty"`
	RetiredAt string `json:"retired_at,omitempty"`
}

func managedActorRegistryPath(crateName string) string {
	return filepath.Join(platform.CratePath("services", crateName), "runtime", "actor-registry.json")
}

func managedActorOwnershipIndexPath() string {
	return platform.CratePath("registry", "managed-actors.json")
}

func managedActorProvisioningStatePath(crateName string) string {
	return filepath.Join(platform.CratePath("services", crateName), "runtime", "actor-provisioning.json")
}

const managedActorTombstoneRetention = 30 * 24 * time.Hour

func appendManagedActorProvisioningEvent(events []managedActorProvisioningEvent, event managedActorProvisioningEvent, limit int) []managedActorProvisioningEvent {
	if limit <= 0 {
		limit = 10
	}
	if strings.TrimSpace(event.At) == "" {
		event.At = actualTimestamp()
	}
	if len(events) > 0 {
		last := events[len(events)-1]
		if last.Provisioning == event.Provisioning && strings.TrimSpace(last.Error) == strings.TrimSpace(event.Error) {
			events[len(events)-1] = event
			return events
		}
	}
	events = append(events, event)
	if len(events) > limit {
		events = append([]managedActorProvisioningEvent(nil), events[len(events)-limit:]...)
	}
	return events
}

func loadManagedActorOwnershipIndex() managedActorOwnershipIndex {
	path := managedActorOwnershipIndexPath()
	data, err := os.ReadFile(path)
	if err != nil {
		return managedActorOwnershipIndex{Actors: []managedActorOwnershipItem{}}
	}
	var index managedActorOwnershipIndex
	if err := json.Unmarshal(data, &index); err != nil {
		return managedActorOwnershipIndex{Actors: []managedActorOwnershipItem{}}
	}
	if index.Actors == nil {
		index.Actors = []managedActorOwnershipItem{}
	}
	return index
}

func pruneExpiredManagedActorTombstones(index managedActorOwnershipIndex, now time.Time) managedActorOwnershipIndex {
	if len(index.Actors) == 0 {
		return index
	}
	filtered := index.Actors[:0]
	for _, actor := range index.Actors {
		if actor.Active {
			filtered = append(filtered, actor)
			continue
		}
		retiredAt := strings.TrimSpace(actor.RetiredAt)
		if retiredAt == "" {
			filtered = append(filtered, actor)
			continue
		}
		ts, err := time.Parse(time.RFC3339, retiredAt)
		if err != nil || now.Sub(ts) <= managedActorTombstoneRetention {
			filtered = append(filtered, actor)
		}
	}
	index.Actors = filtered
	return index
}

func writeManagedActorOwnershipIndex(index managedActorOwnershipIndex) error {
	path := managedActorOwnershipIndexPath()
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	index = pruneExpiredManagedActorTombstones(index, time.Now().UTC())
	index.GeneratedAt = actualTimestamp()
	if index.Actors == nil {
		index.Actors = []managedActorOwnershipItem{}
	}
	data, err := json.MarshalIndent(index, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0644)
}

func writeManagedActorOwnership(crate CrateState) error {
	index := loadManagedActorOwnershipIndex()
	if strings.TrimSpace(crate.Name) == "" || strings.TrimSpace(crate.ActorID) == "" || strings.TrimSpace(crate.ActorUser) == "" || strings.TrimSpace(crate.ExecutionMode) == "" {
		for i := range index.Actors {
			if strings.TrimSpace(index.Actors[i].Crate) != strings.TrimSpace(crate.Name) {
				continue
			}
			index.Actors[i].Active = false
			index.Actors[i].UpdatedAt = actualTimestamp()
			if strings.TrimSpace(index.Actors[i].RetiredAt) == "" {
				index.Actors[i].RetiredAt = actualTimestamp()
			}
		}
		return writeManagedActorOwnershipIndex(index)
	}
	entry := managedActorOwnershipItem{
		Crate:     crate.Name,
		Name:      crate.ActorName,
		Type:      crate.ActorType,
		ID:        crate.ActorID,
		User:      crate.ActorUser,
		Group:     crate.ActorGroup,
		Home:      crate.ActorHome,
		Active:    true,
		UpdatedAt: actualTimestamp(),
	}
	replaced := false
	for i := range index.Actors {
		if strings.TrimSpace(index.Actors[i].Crate) != strings.TrimSpace(crate.Name) {
			continue
		}
		index.Actors[i] = entry
		replaced = true
		break
	}
	if !replaced {
		index.Actors = append(index.Actors, entry)
	}
	if err := writeManagedActorOwnershipIndex(index); err != nil {
		return err
	}
	writeManagedActorOwnershipState(index)
	return nil
}

func pruneManagedActorOwnership(cfg *config.Config) error {
	index := loadManagedActorOwnershipIndex()
	if len(index.Actors) == 0 {
		if err := writeManagedActorOwnershipIndex(index); err != nil {
			return err
		}
		writeManagedActorOwnershipState(index)
		return nil
	}
	activeCrates := map[string]config.ServiceEntry{}
	for _, svc := range cfg.Services.Services {
		activeCrates[strings.TrimSpace(svc.Name)] = svc
	}
	for i := range index.Actors {
		name := strings.TrimSpace(index.Actors[i].Crate)
		if name == "" {
			continue
		}
		svc, ok := activeCrates[name]
		if !ok {
			index.Actors[i].Active = false
			if strings.TrimSpace(index.Actors[i].RetiredAt) == "" {
				index.Actors[i].RetiredAt = actualTimestamp()
			}
			continue
		}
		if strings.TrimSpace(svc.Actor.Name) == "" {
			index.Actors[i].Active = false
			if strings.TrimSpace(index.Actors[i].RetiredAt) == "" {
				index.Actors[i].RetiredAt = actualTimestamp()
			}
			continue
		}
		index.Actors[i].Active = true
		index.Actors[i].RetiredAt = ""
	}
	if err := writeManagedActorOwnershipIndex(index); err != nil {
		return err
	}
	writeManagedActorOwnershipState(index)
	return nil
}

func writeManagedActorProvisioningState(crate CrateState) error {
	if strings.TrimSpace(crate.Name) == "" {
		return nil
	}
	path := managedActorProvisioningStatePath(crate.Name)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	var previous managedActorProvisioningState
	if data, err := os.ReadFile(path); err == nil {
		_ = json.Unmarshal(data, &previous)
	}
	payload := managedActorProvisioningState{
		GeneratedAt:   actualTimestamp(),
		LastSuccessAt: previous.LastSuccessAt,
		LastFailureAt: previous.LastFailureAt,
		Events:        append([]managedActorProvisioningEvent(nil), previous.Events...),
		Provisioning: crate.ActorProvisioning,
		Error:        crate.ActorProvisioningError,
	}
	switch crate.ActorProvisioning {
	case "provisioned":
		payload.LastSuccessAt = payload.GeneratedAt
	case "blocked":
		payload.LastFailureAt = payload.GeneratedAt
	}
	payload.Events = appendManagedActorProvisioningEvent(payload.Events, managedActorProvisioningEvent{
		At:           payload.GeneratedAt,
		Provisioning: crate.ActorProvisioning,
		Error:        crate.ActorProvisioningError,
	}, 10)
	payload.Actor.Name = crate.ActorName
	payload.Actor.Type = crate.ActorType
	payload.Actor.ID = crate.ActorID
	payload.Actor.User = crate.ActorUser
	payload.Actor.Group = crate.ActorGroup
	payload.Actor.Home = crate.ActorHome
	payload.Actor.RuntimeDir = crate.ActorRuntimeDir
	payload.Actor.StateDir = crate.ActorStateDir
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0644)
}

func managedActorClaimedByAnotherCrate(index managedActorOwnershipIndex, crateName, actorID, account string) bool {
	for _, actor := range index.Actors {
		if strings.TrimSpace(actor.Crate) == strings.TrimSpace(crateName) {
			continue
		}
		if !actor.Active {
			continue
		}
		if actorID != "" && strings.TrimSpace(actor.ID) == strings.TrimSpace(actorID) {
			return true
		}
		if account != "" && strings.TrimSpace(actor.User) == strings.TrimSpace(account) {
			return true
		}
	}
	return false
}

func managedActorOwnershipRecord(crateName string) (managedActorOwnershipItem, bool) {
	index := loadManagedActorOwnershipIndex()
	for _, actor := range index.Actors {
		if strings.TrimSpace(actor.Crate) != strings.TrimSpace(crateName) {
			continue
		}
		return actor, true
	}
	return managedActorOwnershipItem{}, false
}

func loadManagedActorRegistry(crateName string) (managedActorRegistryItem, bool) {
	path := managedActorRegistryPath(crateName)
	data, err := os.ReadFile(path)
	if err != nil {
		return managedActorRegistryItem{}, false
	}
	var registry managedActorRegistry
	if err := json.Unmarshal(data, &registry); err != nil {
		return managedActorRegistryItem{}, false
	}
	if strings.TrimSpace(registry.Actor.ID) == "" || strings.TrimSpace(registry.Actor.User) == "" {
		return managedActorRegistryItem{}, false
	}
	return registry.Actor, true
}

func writeManagedActorRegistry(crate CrateState) error {
	if strings.TrimSpace(crate.Name) == "" || strings.TrimSpace(crate.ActorID) == "" || strings.TrimSpace(crate.ActorUser) == "" {
		return nil
	}
	path := managedActorRegistryPath(crate.Name)
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	payload := managedActorRegistry{
		GeneratedAt: actualTimestamp(),
		Actor: managedActorRegistryItem{
			Name:      crate.ActorName,
			Type:      crate.ActorType,
			ID:        crate.ActorID,
			User:      crate.ActorUser,
			Group:     crate.ActorGroup,
			Home:      crate.ActorHome,
			UpdatedAt: actualTimestamp(),
		},
	}
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0644)
}

func resolveManagedActorIdentity(crateName, actorName string) (string, string, string) {
	if registry, ok := loadManagedActorRegistry(crateName); ok {
		return registry.ID, registry.User, valueOrDefault(strings.TrimSpace(registry.Group), registry.User)
	}
	index := loadManagedActorOwnershipIndex()
	seen := map[string]struct{}{}
	for ordinal := 0; ordinal < 16; ordinal++ {
		actorID := managedActorIDSeed(crateName, actorName, ordinal)
		account := managedActorAccountName(actorID, ordinal)
		if account == "" {
			continue
		}
		if _, exists := seen[account]; exists {
			continue
		}
		if managedActorClaimedByAnotherCrate(index, crateName, actorID, account) {
			continue
		}
		seen[account] = struct{}{}
		return actorID, account, account
	}
	return "", "", ""
}

func protectedManagedActorNames() map[string]struct{} {
	protected := map[string]struct{}{
		"root": {}, "admin": {}, "ubuntu": {}, "nobody": {}, "daemon": {},
		"www-data": {}, "crateos-agent": {}, "crateos-policy": {}, "crateos": {},
	}
	cfg, err := config.Load()
	if err == nil && cfg != nil {
		for _, user := range cfg.Users.Users {
			name := strings.ToLower(strings.TrimSpace(user.Name))
			if name != "" {
				protected[name] = struct{}{}
			}
		}
	}
	return protected
}

func managedActorIdentityIssue(crate CrateState) string {
	if crate.ExecutionMode == "" || crate.Module {
		return ""
	}
	if strings.TrimSpace(crate.ActorName) == "" {
		return "managed workload requires actor.name"
	}
	if strings.TrimSpace(crate.ActorID) == "" || strings.TrimSpace(crate.ActorUser) == "" {
		return "managed actor identity could not be allocated"
	}
	if !strings.HasPrefix(strings.TrimSpace(crate.ActorUser), "ca-") {
		return "managed actor runtime account escaped the CrateOS-owned namespace"
	}
	protected := protectedManagedActorNames()
	if _, blocked := protected[strings.ToLower(strings.TrimSpace(crate.ActorUser))]; blocked {
		return "managed actor runtime account collides with a protected identity"
	}
	if _, blocked := protected[strings.ToLower(strings.TrimSpace(crate.ActorGroup))]; blocked {
		return "managed actor runtime group collides with a protected identity"
	}
	return ""
}

func pathExists(path string) bool {
	if strings.TrimSpace(path) == "" {
		return false
	}
	_, err := os.Stat(path)
	return err == nil
}

func applyManagedActorProvisioningPosture(crate *CrateState) {
	crate.ActorProvisioning = ""
	crate.ActorProvisioningError = ""
	crate.ActorProvisioningUpdatedAt = actualTimestamp()
	crate.ActorProvisioningStatePath = ""
	crate.ActorOwnershipStatus = ""
	crate.ActorOwnershipUpdatedAt = ""
	crate.ActorOwnershipRetiredAt = ""
	if crate.ExecutionMode == "" || crate.Module {
		return
	}
	crate.ActorProvisioningStatePath = managedActorProvisioningStatePath(crate.Name)
	if record, ok := managedActorOwnershipRecord(crate.Name); ok {
		if record.Active {
			crate.ActorOwnershipStatus = "claimed"
		} else {
			crate.ActorOwnershipStatus = "retired"
		}
		crate.ActorOwnershipUpdatedAt = record.UpdatedAt
		crate.ActorOwnershipRetiredAt = record.RetiredAt
	}
	if issue := managedActorIdentityIssue(*crate); issue != "" {
		crate.ActorProvisioning = "blocked"
		crate.ActorProvisioningError = issue
		return
	}
	if runtime.GOOS != "linux" {
		crate.ActorProvisioning = "pending"
		return
	}
	if issue := managedActorAdoptionIssue(*crate); issue != "" {
		crate.ActorProvisioning = "blocked"
		crate.ActorProvisioningError = issue
		return
	}
	if linuxAccountExists(crate.ActorUser) && linuxGroupExists(crate.ActorGroup) && pathExists(crate.ActorHome) && pathExists(crate.ActorRuntimeDir) && pathExists(crate.ActorStateDir) {
		crate.ActorProvisioning = "provisioned"
		return
	}
	crate.ActorProvisioning = "pending"
}

func writeExecutionPosture(desired config.ServiceEntry, crate CrateState) {
	runtimeDir := filepath.Join(platform.CratePath("services", desired.Name), "runtime")
	if err := os.MkdirAll(runtimeDir, 0755); err != nil {
		log.Printf("warning: create execution posture dir %s: %v", desired.Name, err)
		return
	}
	path := filepath.Join(runtimeDir, "execution-posture.json")
	payload := map[string]interface{}{
		"generated_at": actualTimestamp(),
		"name":         crate.Name,
		"runtime":      crate.Runtime,
		"adapter":      crate.ExecutionAdapter,
		"mode":         crate.ExecutionMode,
		"status":       crate.ExecutionStatus,
		"actor": map[string]string{
			"name":        crate.ActorName,
			"type":        crate.ActorType,
			"id":          crate.ActorID,
			"user":        crate.ActorUser,
			"group":       crate.ActorGroup,
			"home":        crate.ActorHome,
			"runtime_dir": crate.ActorRuntimeDir,
			"state_dir":   crate.ActorStateDir,
			"provisioning": crate.ActorProvisioning,
			"provisioning_error": crate.ActorProvisioningError,
			"provisioning_updated_at": crate.ActorProvisioningUpdatedAt,
			"provisioning_state_path": crate.ActorProvisioningStatePath,
			"ownership_status": crate.ActorOwnershipStatus,
			"ownership_updated_at": crate.ActorOwnershipUpdatedAt,
			"ownership_retired_at": crate.ActorOwnershipRetiredAt,
		},
		"deploy": map[string]string{
			"source":           crate.DeploySource,
			"upload_path":      crate.UploadPath,
			"working_dir":      crate.WorkingDir,
			"entry":            crate.Entry,
			"install_command":  crate.InstallCommand,
			"environment_file": crate.EnvironmentFile,
		},
		"runtime_objects": map[string]string{
			"primary_unit":        crate.PrimaryUnit,
			"companion_unit":      crate.CompanionUnit,
			"primary_unit_path":   crate.PrimaryUnitPath,
			"companion_unit_path": crate.CompanionUnitPath,
		},
		"execution": map[string]string{
			"start_command":      crate.StartCommand,
			"schedule":           crate.Schedule,
			"timeout":            crate.Timeout,
			"stop_timeout":       crate.StopTimeout,
			"on_timeout":         crate.OnTimeout,
			"kill_signal":        crate.KillSignal,
			"concurrency_policy": crate.ConcurrencyPolicy,
			"summary":            crate.ExecutionSummary,
		},
		"note": "CrateOS is rendering intended execution posture here before full actor lifecycle enforcement, deploy materialization, and stronger execution policy enforcement land.",
	}
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		log.Printf("warning: marshal execution posture %s: %v", desired.Name, err)
		return
	}
	if err := os.WriteFile(path, append(data, '\n'), 0644); err != nil {
		log.Printf("warning: write execution posture %s: %v", desired.Name, err)
	}
}

func inferExecutionArtifactPaths(desired config.ServiceEntry, crate CrateState, hasMod bool) (string, string) {
	if hasMod || crate.ExecutionAdapter != "systemd" || crate.PrimaryUnit == "" {
		return "", ""
	}
	renderedDir := filepath.Join(platform.CratePath("services", desired.Name), "runtime", "rendered", "systemd")
	primaryPath := filepath.Join(renderedDir, crate.PrimaryUnit)
	companionPath := ""
	if crate.CompanionUnit != "" {
		companionPath = filepath.Join(renderedDir, crate.CompanionUnit)
	}
	return primaryPath, companionPath
}

func managedExecutionUnitBase(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	if name == "" {
		return "crateos-managed"
	}
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '-' || r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		out = "managed"
	}
	return "crateos-" + out
}

func desiredManagedUnits(desired config.ServiceEntry, mod modules.Module, hasMod bool) []string {
	if hasMod {
		return crateUnits(desired.Name, mod, hasMod)
	}
	if executionAdapterForRuntime(desired.Runtime) != "systemd" {
		if strings.TrimSpace(desired.Name) == "" {
			return nil
		}
		return []string{desired.Name}
	}
	primary, companion := inferExecutionUnits(desired, mod, hasMod)
	units := []string{}
	if primary != "" {
		units = append(units, primary)
	}
	if companion != "" {
		units = append(units, companion)
	}
	if len(units) == 0 && strings.TrimSpace(desired.Name) != "" {
		units = append(units, desired.Name)
	}
	return units
}

type ReconcileRecord struct {
	GeneratedAt string         `json:"generated_at"`
	Desired     *config.Config `json:"desired"`
	Before      *ActualState   `json:"before"`
	After       *ActualState   `json:"after"`
	Actions     []Action       `json:"actions"`
}

// Reconcile loads config, probes state, computes a diff, applies changes,
// and writes the state files. Returns the list of actions taken.
func Reconcile() ([]Action, error) {
	// Load desired state from config
	cfg, err := config.Load()
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	mods := modules.LoadAll(".")

	// Collect service names from config
	var svcNames []string
	for _, s := range cfg.Services.Services {
		svcNames = append(svcNames, s.Name)
	}
	// Always include CrateOS's own services
	svcNames = appendUnique(svcNames, "crateos-agent", "crateos-policy")

	// Probe actual state
	before := Probe(svcNames)

	// Compute and apply diff
	actions := reconcile(cfg, before, mods)

	// Re-probe after apply so reconcile history captures the transition, not just intent.
	after := Probe(svcNames)

	// Write state files
	if err := writeStateFile("desired.json", cfg); err != nil {
		log.Printf("warning: failed to write desired.json: %v", err)
	}
	if err := writeStateFile("actual.json", after); err != nil {
		log.Printf("warning: failed to write actual.json: %v", err)
	}
	writeServiceStates(after.Services)
	writeCrateStates(cfg, after, mods)
	if err := writeReconcileRecord(cfg, before, after, actions); err != nil {
		log.Printf("warning: failed to write reconcile record: %v", err)
	}

	return actions, nil
}

func RefreshCrateState(name string) error {
	cfg, err := config.Load()
	if err != nil {
		return fmt.Errorf("loading config: %w", err)
	}
	mods := modules.LoadAll(".")
	var desired *config.ServiceEntry
	for i := range cfg.Services.Services {
		if cfg.Services.Services[i].Name == name {
			desired = &cfg.Services.Services[i]
			break
		}
	}
	if desired == nil {
		return fmt.Errorf("service %s not found", name)
	}
	actual := Probe(crateProbeNames(*desired, mods))
	actualByName := make(map[string]ServiceState, len(actual.Services))
	for _, svc := range actual.Services {
		actualByName[svc.Name] = svc
	}
	writeServiceStates(actual.Services)
	writeCrateState(*desired, actualByName, mods)
	return nil
}

func reconcile(cfg *config.Config, actual *ActualState, mods map[string]modules.Module) []Action {
	var actions []Action

	// ── Ensure directories ──
	for _, d := range platform.RequiredDirs {
		if !actual.Directories[d] {
			p := platform.CratePath(d)
			if err := os.MkdirAll(p, 0755); err != nil {
				log.Printf("error: mkdir %s: %v", p, err)
				continue
			}
			actions = append(actions, Action{
				Description: fmt.Sprintf("created directory %s", p),
				Component:   "directory",
				Target:      p,
			})
		}
	}

	// ── Ensure per-service directories ──
	for _, svc := range cfg.Services.Services {
		base := platform.CratePath("services", svc.Name)
		dirs := []string{
			filepath.Join(base, "config"),
			filepath.Join(base, "data"),
			filepath.Join(base, "logs"),
			filepath.Join(base, "runtime"),
			filepath.Join(base, "backups"),
		}
		for _, d := range dirs {
			if err := os.MkdirAll(d, 0755); err != nil {
				log.Printf("error: mkdir %s: %v", d, err)
				continue
			}
			actions = append(actions, Action{
				Description: fmt.Sprintf("ensured service dir %s", d),
				Component:   "directory",
				Target:      d,
			})
		}
	}

	// ── Ensure services ── (Linux only)
	if runtime.GOOS == "linux" {
		for _, desired := range cfg.Services.Services {
			if !desired.Enabled {
				continue
			}
			mod, hasMod := mods[desired.Name]
			targetUnits := crateUnits(desired.Name, mod, hasMod)
			unitStates := crateUnitStates(actual.Services, targetUnits)
			for _, unitState := range unitStates {
				if !unitState.Enabled {
					if err := systemctl("enable", unitState.Name); err == nil {
						actions = append(actions, Action{
							Description: fmt.Sprintf("enabled %s for %s", unitState.Name, desired.Name),
							Component:   "service",
							Target:      unitState.Name,
						})
					}
				}
				if desired.Autostart && !unitState.Active {
					if err := systemctl("start", unitState.Name); err == nil {
						actions = append(actions, Action{
							Description: fmt.Sprintf("started %s for %s", unitState.Name, desired.Name),
							Component:   "service",
							Target:      unitState.Name,
						})
					}
				}
			}

			// If module defines extra units, ensure they are enabled/started too.
			if hasMod && mod.Runtime() == "systemd" {
				for _, pkg := range mod.Spec.Packages {
					if !packageInstalled(pkg) {
						if err := installPackage(pkg); err == nil {
							actions = append(actions, Action{
								Description: fmt.Sprintf("installed package %s for %s", pkg, desired.Name),
								Component:   "package",
								Target:      pkg,
							})
						}
					}
				}
				for _, unit := range modules.ResolveUnits(desired.Name, mod, true) {
					if !containsServiceState(unitStates, unit) {
						_ = systemctl("enable", unit)
						if mod.InstallMode() != "staged" || desired.Autostart {
							_ = systemctl("start", unit)
						}
						actions = append(actions, Action{
							Description: fmt.Sprintf("ensured module unit %s for %s", unit, desired.Name),
							Component:   "service",
							Target:      unit,
						})
					}
				}
				for _, hc := range mod.Spec.HealthChecks {
					if hc.Type == "command" && hc.Command != "" {
						if err := exec.Command("sh", "-c", hc.Command).Run(); err != nil {
							actions = append(actions, Action{
								Description: fmt.Sprintf("health check failed for %s: %s", desired.Name, hc.Command),
								Component:   "health",
								Target:      desired.Name,
							})
						}
					}
				}
			}
		}
		actions = append(actions, activateHostedManagedWorkloads(cfg, actual, mods)...)
	}

	// ── User provisioning ──
	if runtime.GOOS == "linux" {
		_, _, err := users.ProvisionUsers(cfg)
		if err != nil {
			log.Printf("warning: user provisioning failed: %v", err)
		} else {
			actions = append(actions, Action{
				Description: "provisioned CrateOS users to system accounts",
				Component:   "users",
				Target:      "system",
			})
		}
	}

	// ── Platform adapters ──
	actions = append(actions, reconcilePlatform(cfg)...)
	// ── Export symlinks ──
	actions = append(actions, ensureExports()...)

	return actions
}

// ensureExports creates the symlink farm under /srv/crateos/export/.
func ensureExports() []Action {
	if runtime.GOOS != "linux" {
		return nil
	}

	var actions []Action
	links := map[string]string{
		"etc/NetworkManager": "/etc/NetworkManager",
		"etc/nginx":          "/etc/nginx",
		"etc/nftables.conf":  "/etc/nftables.conf",
		"etc/ssh":            "/etc/ssh",
		"var/log/journal":    "/var/log/journal",
	}

	exportBase := platform.CratePath("export")
	_ = os.MkdirAll(exportBase, 0755)
	for rel, target := range links {
		linkPath := filepath.Join(exportBase, rel)

		// Skip if target doesn't exist on this system
		if _, err := os.Stat(target); err != nil {
			continue
		}

		// Skip if link already exists and points correctly
		if existing, err := os.Readlink(linkPath); err == nil && existing == target {
			continue
		}

		// Ensure parent directory
		parent := filepath.Dir(linkPath)
		_ = os.MkdirAll(parent, 0755)

		// Remove stale link if present
		os.Remove(linkPath)

		if err := os.Symlink(target, linkPath); err != nil {
			log.Printf("warning: symlink %s -> %s: %v", linkPath, target, err)
			continue
		}

		actions = append(actions, Action{
			Description: fmt.Sprintf("linked %s -> %s", linkPath, target),
			Component:   "symlink",
			Target:      linkPath,
		})
	}

	return actions
}

func systemctl(action string, unit ...string) error {
	args := []string{action}
	args = append(args, unit...)
	return exec.Command("systemctl", args...).Run()
}

func linuxCommandExists(name string) bool {
	if runtime.GOOS != "linux" {
		return false
	}
	_, err := exec.LookPath(name)
	return err == nil
}

func linuxAccountExists(name string) bool {
	name = strings.TrimSpace(name)
	if runtime.GOOS != "linux" || name == "" {
		return false
	}
	return exec.Command("id", "-u", name).Run() == nil
}

func linuxGroupExists(name string) bool {
	name = strings.TrimSpace(name)
	if runtime.GOOS != "linux" || name == "" {
		return false
	}
	return exec.Command("getent", "group", name).Run() == nil
}

type linuxPasswdEntry struct {
	Name  string
	UID   string
	GID   string
	Group string
	Home  string
	Shell string
}

func readLinuxPasswdEntry(name string) (linuxPasswdEntry, bool) {
	name = strings.TrimSpace(name)
	if runtime.GOOS != "linux" || name == "" {
		return linuxPasswdEntry{}, false
	}
	out, err := exec.Command("getent", "passwd", name).Output()
	if err != nil {
		return linuxPasswdEntry{}, false
	}
	parts := strings.Split(strings.TrimSpace(string(out)), ":")
	if len(parts) < 7 {
		return linuxPasswdEntry{}, false
	}
	groupName := strings.TrimSpace(parts[0])
	if gid := strings.TrimSpace(parts[3]); gid != "" {
		if groupOut, groupErr := exec.Command("getent", "group", gid).Output(); groupErr == nil {
			groupParts := strings.Split(strings.TrimSpace(string(groupOut)), ":")
			if len(groupParts) > 0 && strings.TrimSpace(groupParts[0]) != "" {
				groupName = strings.TrimSpace(groupParts[0])
			}
		}
	}
	return linuxPasswdEntry{
		Name:  strings.TrimSpace(parts[0]),
		UID:   strings.TrimSpace(parts[2]),
		GID:   strings.TrimSpace(parts[3]),
		Group: groupName,
		Home:  strings.TrimSpace(parts[5]),
		Shell: strings.TrimSpace(parts[6]),
	}, true
}

func readLinuxGroupID(name string) string {
	name = strings.TrimSpace(name)
	if runtime.GOOS != "linux" || name == "" {
		return ""
	}
	out, err := exec.Command("getent", "group", name).Output()
	if err != nil {
		return ""
	}
	parts := strings.Split(strings.TrimSpace(string(out)), ":")
	if len(parts) < 3 {
		return ""
	}
	return strings.TrimSpace(parts[2])
}

func readLinuxSupplementaryGroups(name string) []string {
	name = strings.TrimSpace(name)
	if runtime.GOOS != "linux" || name == "" {
		return nil
	}
	out, err := exec.Command("id", "-nG", name).Output()
	if err != nil {
		return nil
	}
	parts := strings.Fields(strings.TrimSpace(string(out)))
	if len(parts) == 0 {
		return nil
	}
	groups := make([]string, 0, len(parts))
	seen := map[string]struct{}{}
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		key := strings.ToLower(part)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		groups = append(groups, part)
	}
	return groups
}

func linuxPathOwnershipIssue(path, expectedUser, expectedGroup string) string {
	path = strings.TrimSpace(path)
	expectedUser = strings.TrimSpace(expectedUser)
	expectedGroup = strings.TrimSpace(expectedGroup)
	if runtime.GOOS != "linux" || path == "" {
		return ""
	}
	info, err := os.Lstat(path)
	if err != nil {
		return ""
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Sprintf("managed actor path %s must not be a symlink", path)
	}
	if !info.IsDir() {
		return fmt.Sprintf("managed actor path %s exists but is not a directory", path)
	}
	if perms := info.Mode().Perm(); perms != 0755 {
		return fmt.Sprintf("managed actor path %s has mode %04o instead of 0755", path, perms)
	}
	return linuxPathEntryOwnershipIssue(path, info, expectedUser, expectedGroup)
}

func linuxPathEntryOwnershipIssue(path string, info os.FileInfo, expectedUser, expectedGroup string) string {
	path = strings.TrimSpace(path)
	expectedUser = strings.TrimSpace(expectedUser)
	expectedGroup = strings.TrimSpace(expectedGroup)
	if runtime.GOOS != "linux" || path == "" || info == nil {
		return ""
	}
	uid, gid, ok := fileInfoOwnershipIDs(info)
	if !ok {
		return fmt.Sprintf("managed actor path %s ownership could not be inspected", path)
	}
	if expectedUser != "" {
		if passwd, exists := readLinuxPasswdEntry(expectedUser); exists && passwd.UID != "" && passwd.UID != fmt.Sprintf("%d", uid) {
			return fmt.Sprintf("managed actor path %s is owned by uid %d instead of actor %s", path, uid, expectedUser)
		}
	}
	if expectedGroup != "" {
		if expectedGID := readLinuxGroupID(expectedGroup); expectedGID != "" && expectedGID != fmt.Sprintf("%d", gid) {
			return fmt.Sprintf("managed actor path %s is owned by gid %d instead of group %s", path, gid, expectedGroup)
		}
	}
	return ""
}

func fileInfoOwnershipIDs(info os.FileInfo) (uint32, uint32, bool) {
	if info == nil || info.Sys() == nil {
		return 0, 0, false
	}
	value := reflect.ValueOf(info.Sys())
	if !value.IsValid() {
		return 0, 0, false
	}
	if value.Kind() == reflect.Pointer {
		if value.IsNil() {
			return 0, 0, false
		}
		value = value.Elem()
	}
	if !value.IsValid() || value.Kind() != reflect.Struct {
		return 0, 0, false
	}
	uidField := value.FieldByName("Uid")
	gidField := value.FieldByName("Gid")
	if !uidField.IsValid() || !gidField.IsValid() {
		return 0, 0, false
	}
	uid, uidOK := numericFieldToUint32(uidField)
	gid, gidOK := numericFieldToUint32(gidField)
	if !uidOK || !gidOK {
		return 0, 0, false
	}
	return uid, gid, true
}

func numericFieldToUint32(field reflect.Value) (uint32, bool) {
	switch field.Kind() {
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return uint32(field.Uint()), true
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		value := field.Int()
		if value < 0 {
			return 0, false
		}
		return uint32(value), true
	default:
		return 0, false
	}
}

func linuxPathEntryPermissionIssue(path string, info os.FileInfo) string {
	path = strings.TrimSpace(path)
	if runtime.GOOS != "linux" || path == "" || info == nil {
		return ""
	}
	perms := info.Mode().Perm()
	if info.IsDir() {
		if perms&0022 != 0 {
			return fmt.Sprintf("managed actor directory %s has writable mode %04o beyond owner-only write", path, perms)
		}
		return ""
	}
	if perms&0022 != 0 {
		return fmt.Sprintf("managed actor file %s has writable mode %04o beyond owner-only write", path, perms)
	}
	return ""
}

func linuxPathRecursiveOwnershipIssue(rootPath, expectedUser, expectedGroup string) string {
	rootPath = strings.TrimSpace(rootPath)
	if runtime.GOOS != "linux" || rootPath == "" {
		return ""
	}
	issueCount := 0
	walkErr := filepath.Walk(rootPath, func(current string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if current == rootPath {
			return nil
		}
		if info.Mode()&os.ModeSymlink != 0 {
			issueCount++
			return fmt.Errorf("managed actor path %s contains symlink %s", rootPath, current)
		}
		if issue := linuxPathEntryOwnershipIssue(current, info, expectedUser, expectedGroup); issue != "" {
			issueCount++
			return fmt.Errorf("%s", issue)
		}
		if issue := linuxPathEntryPermissionIssue(current, info); issue != "" {
			issueCount++
			return fmt.Errorf("%s", issue)
		}
		if issueCount >= 1 {
			return filepath.SkipAll
		}
		return nil
	})
	if walkErr != nil {
		return walkErr.Error()
	}
	return ""
}

func managedActorAdoptionIssue(crate CrateState) string {
	if runtime.GOOS != "linux" || strings.TrimSpace(crate.ActorUser) == "" {
		return ""
	}
	if linuxGroupExists(crate.ActorGroup) && strings.TrimSpace(crate.ActorGroup) != "" {
		if passwd, ok := readLinuxPasswdEntry(crate.ActorGroup); ok && strings.TrimSpace(passwd.Name) != "" {
			return fmt.Sprintf("managed actor runtime group %s collides with an existing user account", crate.ActorGroup)
		}
	}
	if passwd, ok := readLinuxPasswdEntry(crate.ActorUser); ok {
		if expectedGroup := strings.TrimSpace(crate.ActorGroup); expectedGroup != "" && strings.TrimSpace(passwd.Group) != "" && !strings.EqualFold(strings.TrimSpace(passwd.Group), expectedGroup) {
			return fmt.Sprintf("managed actor runtime account %s is bound to existing group %s instead of %s", crate.ActorUser, passwd.Group, expectedGroup)
		}
		if expectedHome := strings.TrimSpace(crate.ActorHome); expectedHome != "" && strings.TrimSpace(passwd.Home) != "" && strings.TrimSpace(passwd.Home) != expectedHome {
			return fmt.Sprintf("managed actor runtime account %s is bound to existing home %s instead of %s", crate.ActorUser, passwd.Home, expectedHome)
		}
		if shell := strings.TrimSpace(passwd.Shell); shell != "" && shell != "/usr/sbin/nologin" && shell != "/usr/bin/nologin" && shell != "/bin/false" {
			return fmt.Sprintf("managed actor runtime account %s is bound to existing shell %s instead of a non-login shell", crate.ActorUser, shell)
		}
	}
	if groups := readLinuxSupplementaryGroups(crate.ActorUser); len(groups) > 0 {
		expectedGroup := strings.TrimSpace(crate.ActorGroup)
		for _, group := range groups {
			group = strings.TrimSpace(group)
			if group == "" {
				continue
			}
			if expectedGroup != "" && strings.EqualFold(group, expectedGroup) {
				continue
			}
			if strings.EqualFold(group, strings.TrimSpace(crate.ActorUser)) {
				continue
			}
			return fmt.Sprintf("managed actor runtime account %s has unexpected supplementary group %s", crate.ActorUser, group)
		}
	}
	for _, actorPath := range []string{crate.ActorHome, crate.ActorRuntimeDir, crate.ActorStateDir} {
		if issue := linuxPathOwnershipIssue(actorPath, crate.ActorUser, crate.ActorGroup); issue != "" {
			return issue
		}
		if issue := linuxPathRecursiveOwnershipIssue(actorPath, crate.ActorUser, crate.ActorGroup); issue != "" {
			return issue
		}
	}
	return ""
}

func ensureLinuxGroup(name string) error {
	name = strings.TrimSpace(name)
	if runtime.GOOS != "linux" || name == "" {
		return nil
	}
	if linuxGroupExists(name) {
		return nil
	}
	if !linuxCommandExists("groupadd") {
		return fmt.Errorf("groupadd not available while provisioning managed group %s", name)
	}
	return exec.Command("groupadd", "--system", name).Run()
}

func ensureLinuxAccount(user, group, home string) error {
	user = strings.TrimSpace(user)
	group = strings.TrimSpace(group)
	home = strings.TrimSpace(home)
	if runtime.GOOS != "linux" || user == "" {
		return nil
	}
	if linuxAccountExists(user) {
		return nil
	}
	if !linuxCommandExists("useradd") {
		return fmt.Errorf("useradd not available while provisioning managed actor %s", user)
	}
	args := []string{"--system", "--no-create-home"}
	if group != "" {
		args = append(args, "--gid", group)
	}
	if home != "" {
		args = append(args, "--home-dir", home)
	}
	args = append(args, "--shell", "/usr/sbin/nologin", user)
	return exec.Command("useradd", args...).Run()
}

func ensureOwnedDirectory(path string, perm os.FileMode, owner string) error {
	path = strings.TrimSpace(path)
	owner = strings.TrimSpace(owner)
	if path == "" {
		return nil
	}
	if err := os.MkdirAll(path, perm); err != nil {
		return err
	}
	if runtime.GOOS != "linux" || owner == "" {
		return nil
	}
	if !linuxCommandExists("chown") {
		return fmt.Errorf("chown not available while preparing %s", path)
	}
	return exec.Command("chown", "-R", owner+":"+owner, path).Run()
}

func prepareHostedManagedActor(desired config.ServiceEntry, crate CrateState) ([]Action, []string) {
	actions := []Action{}
	issues := []string{}
	if runtime.GOOS != "linux" || crate.ExecutionAdapter != "systemd" || crate.Module {
		return actions, issues
	}
	if issue := managedActorIdentityIssue(crate); issue != "" {
		issues = append(issues, issue)
		return actions, issues
	}
	if issue := managedActorAdoptionIssue(crate); issue != "" {
		issues = append(issues, issue)
		return actions, issues
	}
	if strings.TrimSpace(crate.ActorUser) == "" {
		issues = append(issues, fmt.Sprintf("managed actor provisioning requires actor identity for %s", desired.Name))
		return actions, issues
	}
	groupExists := linuxGroupExists(crate.ActorGroup)
	if err := ensureLinuxGroup(crate.ActorGroup); err != nil {
		issues = append(issues, fmt.Sprintf("provision managed group %s: %v", crate.ActorGroup, err))
	} else if crate.ActorGroup != "" && !groupExists {
		actions = append(actions, Action{
			Description: fmt.Sprintf("ensured managed actor group %s for %s", crate.ActorGroup, desired.Name),
			Component:   "service",
			Target:      crate.ActorGroup,
		})
	}
	accountExists := linuxAccountExists(crate.ActorUser)
	if err := ensureLinuxAccount(crate.ActorUser, crate.ActorGroup, crate.ActorHome); err != nil {
		issues = append(issues, fmt.Sprintf("provision managed actor %s: %v", crate.ActorUser, err))
	} else if !accountExists {
		actions = append(actions, Action{
			Description: fmt.Sprintf("ensured managed actor %s for %s", crate.ActorUser, desired.Name),
			Component:   "service",
			Target:      crate.ActorUser,
		})
	}
	for _, dir := range []struct {
		path string
		name string
	}{
		{path: crate.ActorHome, name: "actor home"},
		{path: crate.ActorRuntimeDir, name: "actor runtime"},
		{path: crate.ActorStateDir, name: "actor state"},
	} {
		if strings.TrimSpace(dir.path) == "" {
			continue
		}
		_, existed := os.Stat(dir.path)
		if err := ensureOwnedDirectory(dir.path, 0755, crate.ActorUser); err != nil {
			issues = append(issues, fmt.Sprintf("prepare %s for %s: %v", dir.name, desired.Name, err))
			continue
		}
		if os.IsNotExist(existed) {
			actions = append(actions, Action{
				Description: fmt.Sprintf("ensured %s dir %s for %s", dir.name, dir.path, desired.Name),
				Component:   "directory",
				Target:      dir.path,
			})
		}
	}
	return actions, issues
}

func packageInstalled(pkg string) bool {
	if runtime.GOOS != "linux" {
		return false
	}
	return exec.Command("dpkg-query", "-W", "-f=${Status}", pkg).Run() == nil
}

func installPackage(pkg string) error {
	if runtime.GOOS != "linux" {
		return fmt.Errorf("package install unsupported on %s", runtime.GOOS)
	}
	return exec.Command("apt-get", "install", "-y", pkg).Run()
}

func writeStateFile(name string, data interface{}) error {
	path := platform.CratePath("state", name)
	b, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, b, 0644)
}

func writeReconcileRecord(cfg *config.Config, before *ActualState, after *ActualState, actions []Action) error {
	record := ReconcileRecord{
		GeneratedAt: actualTimestamp(),
		Desired:     cfg,
		Before:      before,
		After:       after,
		Actions:     append([]Action(nil), actions...),
	}
	b, err := json.MarshalIndent(record, "", "  ")
	if err != nil {
		return err
	}

	stateDir := platform.CratePath("state")
	lastGoodDir := platform.CratePath("state", "last-good")
	if err := os.MkdirAll(stateDir, 0755); err != nil {
		return err
	}
	if err := os.MkdirAll(lastGoodDir, 0755); err != nil {
		return err
	}

	latestPath := filepath.Join(stateDir, "reconcile-latest.json")
	historyPath := filepath.Join(lastGoodDir, fmt.Sprintf("reconcile-%s.json", time.Now().UTC().Format("20060102T150405Z")))
	if err := os.WriteFile(latestPath, b, 0644); err != nil {
		return err
	}
	return os.WriteFile(historyPath, b, 0644)
}
func writeServiceStates(services []ServiceState) {
	for _, svc := range services {
		base := platform.CratePath("services", svc.Name)
		_ = os.MkdirAll(base, 0755)
		path := filepath.Join(base, "state.json")
		b, err := json.MarshalIndent(svc, "", "  ")
		if err != nil {
			log.Printf("warning: marshal service state %s: %v", svc.Name, err)
			continue
		}
		if err := os.WriteFile(path, b, 0644); err != nil {
			log.Printf("warning: write service state %s: %v", svc.Name, err)
		}
	}
}

func writeCrateStates(cfg *config.Config, actual *ActualState, mods map[string]modules.Module) {
	actualByName := make(map[string]ServiceState, len(actual.Services))
	for _, svc := range actual.Services {
		actualByName[svc.Name] = svc
	}

	for _, desired := range cfg.Services.Services {
		writeCrateState(desired, actualByName, mods)
	}
	if err := pruneManagedActorOwnership(cfg); err != nil {
		log.Printf("warning: prune actor ownership index: %v", err)
	}
}

func buildCrateState(desired config.ServiceEntry, actualByName map[string]ServiceState, mod modules.Module, hasMod bool) CrateState {
	crate := CrateState{
		Name:        desired.Name,
		DisplayName: desired.Name,
		Runtime:     modules.ResolveRuntime(desired.Runtime, mod, hasMod),
		Desired:     desired.Enabled,
		Autostart:   desired.Autostart,
		Status:      "unknown",
		Health:      "unknown",
		Ready:       !desired.Enabled,
	}
	applyManagedExecutionMetadata(&crate, desired, mod, hasMod)
	applyManagedActorProvisioningPosture(&crate)

	if hasMod {
		crate.Module = true
		crate.DisplayName = mod.DisplayName()
		crate.Category = mod.Metadata.Category
		crate.Description = mod.Metadata.Description
		crate.InstallMode = modules.ResolveInstallMode(mod, true)
		crate.UnitNames = modules.ResolveUnits(desired.Name, mod, true)
		crate.DataPath = strings.TrimSpace(mod.Spec.Paths.Data.Canonical)
		crate.NativeDataPath = strings.TrimSpace(mod.Spec.Paths.Data.Native)
		crate.Stateful = crate.DataPath != "" || crate.NativeDataPath != ""
		if crate.Stateful {
			switch {
			case crate.DataPath != "" && crate.NativeDataPath != "":
				crate.StorageSummary = fmt.Sprintf("canonical data path %s maps to native %s", crate.DataPath, crate.NativeDataPath)
			case crate.DataPath != "":
				crate.StorageSummary = "canonical data path " + crate.DataPath
			case crate.NativeDataPath != "":
				crate.StorageSummary = "native data path " + crate.NativeDataPath
			}
		}
		for _, unit := range crate.UnitNames {
			if unitState, ok := actualByName[unit]; ok {
				crate.Units = append(crate.Units, unitState)
			} else {
				crate.Units = append(crate.Units, ServiceState{Name: unit, Status: "unknown", Health: "unknown"})
			}
		}
		crate.PackagesInstalled = true
		for _, pkg := range mod.Spec.Packages {
			if !packageInstalled(pkg) {
				crate.PackagesInstalled = false
				crate.MissingPackages = append(crate.MissingPackages, pkg)
			}
		}
		for _, hc := range mod.Spec.HealthChecks {
			if hc.Command != "" {
				crate.HealthChecks = append(crate.HealthChecks, hc.Command)
			}
		}
	} else {
		for _, unit := range desiredManagedUnits(desired, mod, hasMod) {
			if svc, ok := actualByName[unit]; ok {
				crate.Units = append(crate.Units, svc)
			} else {
				crate.Units = append(crate.Units, ServiceState{Name: unit, Status: "unknown", Health: "unknown"})
			}
		}
		crate.PackagesInstalled = true
		if strings.TrimSpace(desired.Runtime) == "docker" {
			crate.StorageSummary = "runtime-managed data path depends on the selected service implementation"
		}
	}

	waitingForExplicitStart := hasMod && mod.InstallMode() == "staged" && desired.Enabled && !desired.Autostart
	if waitingForExplicitStart {
		crate.Status = "staged"
		crate.Health = "pending"
		crate.Summary = "waiting for explicit start"
	} else {
		crate.Status = aggregateCrateStatus(crate.Units)
		crate.Health = aggregateCrateHealth(crate.Units)
		crate.Summary = summarizeCrateUnits(crate.Units)
	}

	ready := desired.Enabled
	if !desired.Enabled {
		ready = true
	}
	if desired.Enabled {
		if hasMod {
			if !crate.PackagesInstalled {
				ready = false
			}
			if !waitingForExplicitStart {
				for _, unit := range crate.Units {
					if !unit.Active {
						ready = false
					}
					if unit.Health != "ok" {
						ready = false
					}
				}
			}
		} else {
			primary := actualByName[desired.Name]
			if len(crate.Units) > 0 {
				primary = crate.Units[0]
			}
			ready = primary.Active
		}
	}
	crate.Ready = ready
	if desired.Enabled && !ready && crate.LastError == "" {
		if len(crate.MissingPackages) > 0 {
			crate.LastError = "missing packages: " + strings.Join(crate.MissingPackages, ", ")
		} else if crate.Status == "partial" {
			crate.LastError = "crate units are not in a consistent running state"
		} else if crate.Health != "ok" && crate.Health != "pending" {
			crate.LastError = "service health is " + crate.Health
		}
	}
	validationIssues := validateManagedExecutionPolicy(crate)
	if len(validationIssues) > 0 {
		crate.Health = "degraded"
		if crate.Status == "" || crate.Status == "unknown" {
			crate.Status = "partial"
		}
		crate.Ready = false
		if crate.LastError == "" {
			crate.LastError = validationIssues[0]
		}
		if crate.Summary == "" || crate.Summary == "rendered desired state successfully" {
			crate.Summary = validationIssues[0]
		}
	}
	if crate.DisplayName == "" {
		crate.DisplayName = desired.Name
	}
	if crate.ActorProvisioningError != "" && crate.LastError == "" {
		crate.LastError = crate.ActorProvisioningError
	}
	crate.LastAction = inferCrateLastAction(desired, crate, waitingForExplicitStart)
	crate.LastActionAt = actualTimestamp()
	crate.SuggestedRepair = inferCrateSuggestedRepair(crate, waitingForExplicitStart)
	return crate
}

func inferCrateLastAction(desired config.ServiceEntry, crate CrateState, waitingForExplicitStart bool) string {
	switch {
	case !desired.Enabled:
		return "disable"
	case len(crate.MissingPackages) > 0:
		return "install"
	case waitingForExplicitStart:
		return "enable"
	case crate.Status == "failed" || crate.Status == "partial":
		return "start"
	case desired.Autostart:
		return "reconcile"
	default:
		return "configure"
	}
}

func inferCrateSuggestedRepair(crate CrateState, waitingForExplicitStart bool) string {
	switch {
	case crate.ActorProvisioning == "blocked":
		return "repair managed actor identity policy before reconcile can continue"
	case crate.ActorProvisioning == "pending" && crate.ExecutionMode != "":
		return "run reconcile to provision the managed actor runtime identity"
	case crate.ActorName == "" && crate.ExecutionMode != "":
		return "assign a managed actor for this workload"
	case crate.ExecutionMode == "job" && crate.Schedule == "":
		return "set a schedule before enabling recurring job execution"
	case crate.ExecutionMode != "" && crate.StartCommand == "" && !crate.Module:
		return "set a start command or bind the workload to a module-defined runtime"
	case len(crate.MissingPackages) > 0:
		return "repair dependencies and rerun reconcile"
	case waitingForExplicitStart:
		return "start crate explicitly after staged install"
	case crate.Status == "failed":
		return "inspect unit failures and rerun reconcile"
	case crate.Status == "partial":
		return "repair inconsistent units and rerun reconcile"
	case crate.Health == "degraded":
		return "run health checks and repair dependent resources"
	default:
		return ""
	}
}

func applyManagedExecutionMetadata(crate *CrateState, desired config.ServiceEntry, mod modules.Module, hasMod bool) {
	crate.ActorName = strings.TrimSpace(desired.Actor.Name)
	crate.ActorType = strings.TrimSpace(desired.Actor.Type)
	// TODO: Split desired actor identity posture from provisioned native account state once reconcile can detect collisions and lifecycle failures.
	crate.ActorID, crate.ActorUser, crate.ActorGroup = resolveManagedActorIdentity(desired.Name, crate.ActorName)
	if crate.ActorUser != "" {
		crate.ActorHome = filepath.Join(platform.CratePath("services", desired.Name), "runtime", "actors", crate.ActorUser)
		crate.ActorRuntimeDir = filepath.Join(crate.ActorHome, "run")
		crate.ActorStateDir = filepath.Join(crate.ActorHome, "state")
	}
	crate.DeploySource = strings.TrimSpace(desired.Deploy.Source)
	crate.UploadPath = strings.TrimSpace(desired.Deploy.UploadPath)
	crate.WorkingDir = strings.TrimSpace(desired.Deploy.WorkingDir)
	crate.Entry = strings.TrimSpace(desired.Deploy.Entry)
	crate.InstallCommand = strings.TrimSpace(desired.Deploy.InstallCmd)
	crate.EnvironmentFile = strings.TrimSpace(desired.Deploy.EnvFile)
	crate.ExecutionMode = normalizeExecutionMode(desired.Execution.Mode, desired.Runtime)
	crate.ExecutionAdapter = executionAdapterForRuntime(desired.Runtime)
	crate.ExecutionStatus = inferExecutionStatus(desired, hasMod)
	crate.PrimaryUnit, crate.CompanionUnit = inferExecutionUnits(desired, mod, hasMod)
	crate.ExecutionStatePath = filepath.Join(platform.CratePath("services", desired.Name), "runtime", "execution-posture.json")
	crate.StartCommand = strings.TrimSpace(desired.Execution.StartCmd)
	crate.Schedule = strings.TrimSpace(desired.Execution.Schedule)
	crate.Timeout = normalizeDurationField(desired.Execution.Timeout, "0")
	crate.StopTimeout = normalizeDurationField(desired.Execution.StopTimeout, "30s")
	crate.OnTimeout = normalizeTimeoutBehavior(desired.Execution.OnTimeout)
	crate.KillSignal = normalizeKillSignal(desired.Execution.KillSignal)
	crate.ConcurrencyPolicy = normalizeConcurrencyPolicy(desired.Execution.Concurrency)
	crate.PrimaryUnitPath, crate.CompanionUnitPath = inferExecutionArtifactPaths(desired, *crate, hasMod)
	crate.ExecutionSummary = summarizeExecutionPolicy(*crate)
}

func validateManagedExecutionPolicy(crate CrateState) []string {
	issues := []string{}
	if crate.ActorName == "" {
		issues = append(issues, "managed workload requires actor.name")
	}
	if crate.ExecutionMode == "job" && crate.Schedule == "" {
		issues = append(issues, "job execution requires execution.schedule")
	}
	if crate.ExecutionMode == "job" && crate.StartCommand == "" {
		issues = append(issues, "job execution requires execution.start_cmd")
	}
	if crate.DeploySource == "upload" && crate.UploadPath == "" {
		issues = append(issues, "upload deploy source requires deploy.upload_path")
	}
	if crate.DeploySource == "upload" && crate.WorkingDir == "" {
		issues = append(issues, "upload deploy source requires deploy.working_dir")
	}
	if crate.ExecutionMode == "service" && crate.StartCommand == "" && !crate.Module {
		issues = append(issues, "service execution without a module runtime requires execution.start_cmd")
	}
	return issues
}

func normalizeExecutionMode(mode, runtimeName string) string {
	mode = strings.ToLower(strings.TrimSpace(mode))
	switch mode {
	case "service", "job":
		return mode
	}
	if strings.EqualFold(strings.TrimSpace(runtimeName), "task") {
		return "job"
	}
	return "service"
}

func normalizeDurationField(value, fallback string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return fallback
	}
	return value
}

func normalizeTimeoutBehavior(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "", "kill":
		return "kill"
	default:
		return strings.ToLower(strings.TrimSpace(value))
	}
}

func normalizeKillSignal(value string) string {
	switch strings.ToUpper(strings.TrimSpace(value)) {
	case "", "SIGTERM":
		return "SIGTERM"
	default:
		return strings.ToUpper(strings.TrimSpace(value))
	}
}

func normalizeConcurrencyPolicy(value string) string {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "", "replace":
		return "replace"
	case "forbid":
		return "forbid"
	default:
		return strings.ToLower(strings.TrimSpace(value))
	}
}

func summarizeExecutionPolicy(crate CrateState) string {
	parts := []string{}
	if crate.ActorName != "" {
		parts = append(parts, "actor "+crate.ActorName)
	}
	if crate.ExecutionMode != "" {
		parts = append(parts, "mode "+crate.ExecutionMode)
	}
	if crate.Schedule != "" {
		parts = append(parts, "schedule "+crate.Schedule)
	}
	if crate.Timeout != "" {
		parts = append(parts, "timeout "+crate.Timeout)
	}
	if crate.ConcurrencyPolicy != "" {
		parts = append(parts, "overlap "+crate.ConcurrencyPolicy)
	}
	if crate.ExecutionStatus != "" {
		parts = append(parts, "runtime "+crate.ExecutionStatus)
	}
	return strings.Join(parts, " · ")
}

func executionAdapterForRuntime(runtimeName string) string {
	switch strings.ToLower(strings.TrimSpace(runtimeName)) {
	case "docker":
		return "docker"
	default:
		return "systemd"
	}
}

func inferExecutionStatus(desired config.ServiceEntry, hasMod bool) string {
	if hasMod {
		return "module-owned"
	}
	if normalizeExecutionMode(desired.Execution.Mode, desired.Runtime) == "job" && translateExecutionSchedule(strings.TrimSpace(desired.Execution.Schedule)) == "" {
		return "schedule-invalid"
	}
	switch normalizeExecutionMode(desired.Execution.Mode, desired.Runtime) {
	case "job":
		return "native-timer"
	default:
		return "native-service"
	}
}

func inferExecutionUnits(desired config.ServiceEntry, mod modules.Module, hasMod bool) (string, string) {
	if hasMod {
		units := modules.ResolveUnits(desired.Name, mod, true)
		switch len(units) {
		case 0:
			return "", ""
		case 1:
			return units[0], ""
		default:
			return units[0], units[1]
		}
	}
	name := strings.TrimSpace(desired.Name)
	if name == "" {
		return "", ""
	}
	switch normalizeExecutionMode(desired.Execution.Mode, desired.Runtime) {
	case "job":
		base := managedExecutionUnitBase(name)
		return base + ".service", base + ".timer"
	default:
		base := managedExecutionUnitBase(name)
		return base + ".service", ""
	}
}

func hasModule(mods map[string]modules.Module, name string) bool {
	_, ok := mods[name]
	return ok
}

func writeCrateState(desired config.ServiceEntry, actualByName map[string]ServiceState, mods map[string]modules.Module) {
	mod, hasMod := mods[desired.Name]
	crate := buildCrateState(desired, actualByName, mod, hasMod)
	payload := StoredCrateState{
		GeneratedAt: actualTimestamp(),
		Crate:       crate,
	}
	base := platform.CratePath("services", desired.Name)
	_ = os.MkdirAll(base, 0755)
	path := filepath.Join(base, "crate-state.json")
	if err := preservePreviousStableCrateState(path, base); err != nil {
		log.Printf("warning: preserve last-good crate state %s: %v", desired.Name, err)
	}
	b, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		log.Printf("warning: marshal crate state %s: %v", desired.Name, err)
		return
	}
	if err := os.WriteFile(path, b, 0644); err != nil {
		log.Printf("warning: write crate state %s: %v", desired.Name, err)
	}
	if err := writeManagedActorProvisioningState(crate); err != nil {
		log.Printf("warning: write actor provisioning state %s: %v", desired.Name, err)
	}
	if err := writeManagedActorRegistry(crate); err != nil {
		log.Printf("warning: write actor registry %s: %v", desired.Name, err)
	}
	if err := writeManagedActorOwnership(crate); err != nil {
		log.Printf("warning: write actor ownership %s: %v", desired.Name, err)
	}
	writeExecutionPosture(desired, crate)
	writeManagedExecutionArtifacts(desired, crate, hasMod)
	applyManagedExecutionNativeState(desired, crate, hasMod)
}

func preservePreviousStableCrateState(currentPath string, crateBase string) error {
	b, err := os.ReadFile(currentPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	var stored StoredCrateState
	if err := json.Unmarshal(b, &stored); err != nil {
		return err
	}
	if !isStableCrateState(stored.Crate) {
		return nil
	}
	lastGoodDir := filepath.Join(crateBase, "runtime", "last-good")
	if err := os.MkdirAll(lastGoodDir, 0755); err != nil {
		return err
	}
	lastGoodPath := filepath.Join(lastGoodDir, "crate-state.json")
	return os.WriteFile(lastGoodPath, b, 0644)
}

func isStableCrateState(crate CrateState) bool {
	switch crate.Status {
	case "active", "running", "inactive", "disabled", "staged":
	default:
		return false
	}

	switch crate.Health {
	case "", "ok", "pending", "unknown":
	default:
		return false
	}

	return strings.TrimSpace(crate.LastError) == ""
}

func crateProbeNames(desired config.ServiceEntry, mods map[string]modules.Module) []string {
	mod, ok := mods[desired.Name]
	names := desiredManagedUnits(desired, mod, ok)
	names = appendUnique(names, "crateos-agent", "crateos-policy")
	return names
}

func aggregateCrateStatus(units []ServiceState) string {
	if len(units) == 0 {
		return "unknown"
	}
	activeCount := 0
	failedCount := 0
	unknownCount := 0
	for _, unit := range units {
		switch unit.Status {
		case "failed":
			failedCount++
		case "active", "running":
			activeCount++
		case "", "unknown":
			unknownCount++
		}
	}
	switch {
	case failedCount > 0:
		return "failed"
	case activeCount == len(units):
		return "active"
	case activeCount > 0:
		return "partial"
	case unknownCount == len(units):
		return "unknown"
	default:
		return "inactive"
	}
}

func aggregateCrateHealth(units []ServiceState) string {
	if len(units) == 0 {
		return "unknown"
	}
	allOK := true
	for _, unit := range units {
		if unit.Health == "degraded" {
			return "degraded"
		}
		if unit.Health != "ok" {
			allOK = false
		}
	}
	if allOK {
		return "ok"
	}
	return "unknown"
}

func summarizeCrateUnits(units []ServiceState) string {
	if len(units) == 0 {
		return ""
	}
	activeCount := 0
	enabledCount := 0
	failed := make([]string, 0)
	inactive := make([]string, 0)
	for _, unit := range units {
		if unit.Active {
			activeCount++
		}
		if unit.Enabled {
			enabledCount++
		}
		if unit.Status == "failed" {
			failed = append(failed, unit.Name)
			continue
		}
		if !unit.Active {
			inactive = append(inactive, unit.Name)
		}
	}
	switch {
	case len(failed) > 0:
		return "failed units: " + strings.Join(failed, ", ")
	case activeCount > 0 && activeCount < len(units):
		return fmt.Sprintf("partially active (%d/%d units running)", activeCount, len(units))
	case enabledCount > 0 && enabledCount < len(units):
		return fmt.Sprintf("partially enabled (%d/%d units enabled)", enabledCount, len(units))
	case len(inactive) == len(units):
		return "all units inactive"
	default:
		return ""
	}
}

func crateUnits(name string, mod modules.Module, hasMod bool) []string {
	if units := modules.ResolveUnits(name, mod, hasMod); len(units) > 0 {
		return units
	}
	return nil
}

func crateUnitStates(actual []ServiceState, units []string) []ServiceState {
	states := make([]ServiceState, 0, len(units))
	for _, unit := range units {
		found := false
		for _, svc := range actual {
			if svc.Name == unit {
				states = append(states, svc)
				found = true
				break
			}
		}
		if !found {
			states = append(states, ServiceState{Name: unit, Status: "unknown", Health: "unknown"})
		}
	}
	return states
}

func containsServiceState(states []ServiceState, name string) bool {
	for _, state := range states {
		if state.Name == name {
			return true
		}
	}
	return false
}

func appendUnique(slice []string, items ...string) []string {
	seen := make(map[string]bool, len(slice))
	for _, s := range slice {
		seen[s] = true
	}
	for _, item := range items {
		if !seen[item] {
			slice = append(slice, item)
			seen[item] = true
		}
	}
	return slice
}

func applyManagedExecutionNativeState(desired config.ServiceEntry, crate CrateState, hasMod bool) {
	if runtime.GOOS != "linux" || hasMod || crate.ExecutionAdapter != "systemd" {
		return
	}
	_, _, _ = syncManagedExecutionNativeUnits(desired, crate)
}

func syncManagedExecutionNativeUnits(desired config.ServiceEntry, crate CrateState) ([]Action, bool, []string) {
	actions := []Action{}
	reloaded := false
	issues := []string{}
	provisionActions, provisionIssues := prepareHostedManagedActor(desired, crate)
	actions = append(actions, provisionActions...)
	if len(provisionIssues) > 0 {
		issues = append(issues, provisionIssues...)
		return actions, reloaded, issues
	}
	// TODO: Materialize deploy uploads before copying units into /etc/systemd/system.
	primaryNativePath := managedNativeUnitPath(crate.PrimaryUnit)
	if crate.PrimaryUnitPath != "" && primaryNativePath != "" {
		if action, err := syncManagedArtifact(filepath.ToSlash(filepath.Join("native/services", desired.Name, crate.PrimaryUnit)), crate.PrimaryUnitPath, primaryNativePath, "service", fmt.Sprintf("installed hosted workload unit %s", crate.PrimaryUnit)); err != nil {
			issues = append(issues, err.Error())
		} else if action != nil {
			actions = append(actions, *action)
			reloaded = true
		}
	}
	companionNativePath := managedNativeUnitPath(crate.CompanionUnit)
	if crate.CompanionUnitPath != "" && companionNativePath != "" {
		if action, err := syncManagedArtifact(filepath.ToSlash(filepath.Join("native/services", desired.Name, crate.CompanionUnit)), crate.CompanionUnitPath, companionNativePath, "service", fmt.Sprintf("installed hosted workload timer %s", crate.CompanionUnit)); err != nil {
			issues = append(issues, err.Error())
		} else if action != nil {
			actions = append(actions, *action)
			reloaded = true
		}
	}
	if !desired.Enabled {
		if action, err := removeManagedArtifact(filepath.ToSlash(filepath.Join("native/services", desired.Name, crate.PrimaryUnit)), primaryNativePath, "service", fmt.Sprintf("removed hosted workload unit %s", crate.PrimaryUnit)); err != nil {
			issues = append(issues, err.Error())
		} else if action != nil {
			actions = append(actions, *action)
			reloaded = true
		}
		if companionNativePath != "" {
			if action, err := removeManagedArtifact(filepath.ToSlash(filepath.Join("native/services", desired.Name, crate.CompanionUnit)), companionNativePath, "service", fmt.Sprintf("removed hosted workload timer %s", crate.CompanionUnit)); err != nil {
				issues = append(issues, err.Error())
			} else if action != nil {
				actions = append(actions, *action)
				reloaded = true
			}
		}
	}
	return actions, reloaded, issues
}

func managedNativeUnitPath(unit string) string {
	unit = strings.TrimSpace(unit)
	if unit == "" {
		return ""
	}
	return filepath.Join("/etc/systemd/system", unit)
}

func activateHostedManagedWorkloads(cfg *config.Config, actual *ActualState, mods map[string]modules.Module) []Action {
	if runtime.GOOS != "linux" {
		return nil
	}
	var actions []Action
	var reloadNeeded bool
	actualByName := make(map[string]ServiceState, len(actual.Services))
	for _, svc := range actual.Services {
		actualByName[svc.Name] = svc
	}
	for _, desired := range cfg.Services.Services {
		mod, hasMod := mods[desired.Name]
		if hasMod {
			continue
		}
		crate := buildCrateState(desired, actualByName, mod, hasMod)
		// TODO: Stop rebuilding transient crate state twice once apply can persist provisioning results back into runtime posture.
		syncActions, reloaded, issues := syncManagedExecutionNativeUnits(desired, crate)
		actions = append(actions, syncActions...)
		if len(issues) > 0 {
			continue
		}
		if reloaded {
			reloadNeeded = true
		}
	}
	if reloadNeeded {
		if err := systemctl("daemon-reload"); err == nil {
			actions = append(actions, Action{Description: "reloaded systemd after hosted workload unit changes", Component: "service", Target: "systemd"})
		}
	}
	for _, desired := range cfg.Services.Services {
		mod, hasMod := mods[desired.Name]
		if hasMod || !desired.Enabled {
			continue
		}
		crate := buildCrateState(desired, actualByName, mod, hasMod)
		actions = append(actions, activateHostedManagedUnits(desired, crate, actualByName)...)
	}
	return actions
}

func activateHostedManagedUnits(desired config.ServiceEntry, crate CrateState, actualByName map[string]ServiceState) []Action {
	var actions []Action
	switch crate.ExecutionMode {
	case "job":
		timerName := crate.CompanionUnit
		if timerName == "" || translateExecutionSchedule(crate.Schedule) == "" {
			return actions
		}
		if _, issues := prepareHostedManagedActor(desired, crate); len(issues) > 0 {
			return actions
		}
		// TODO: Enforce CrateOS concurrency and timeout policy for jobs explicitly; timer activation alone does not guarantee overlap behavior.
		timerState := actualByName[timerName]
		if !timerState.Enabled {
			if err := systemctl("enable", timerName); err == nil {
				actions = append(actions, Action{Description: fmt.Sprintf("enabled hosted workload timer %s for %s", timerName, desired.Name), Component: "service", Target: timerName})
			}
		}
		if !timerState.Active {
			if err := systemctl("start", timerName); err == nil {
				actions = append(actions, Action{Description: fmt.Sprintf("started hosted workload timer %s for %s", timerName, desired.Name), Component: "service", Target: timerName})
			}
		}
	default:
		serviceName := crate.PrimaryUnit
		if serviceName == "" {
			return actions
		}
		if _, issues := prepareHostedManagedActor(desired, crate); len(issues) > 0 {
			return actions
		}
		serviceState := actualByName[serviceName]
		if !serviceState.Enabled {
			if err := systemctl("enable", serviceName); err == nil {
				actions = append(actions, Action{Description: fmt.Sprintf("enabled hosted workload service %s for %s", serviceName, desired.Name), Component: "service", Target: serviceName})
			}
		}
		if desired.Autostart && !serviceState.Active {
			if err := systemctl("start", serviceName); err == nil {
				actions = append(actions, Action{Description: fmt.Sprintf("started hosted workload service %s for %s", serviceName, desired.Name), Component: "service", Target: serviceName})
			}
		}
	}
	return actions
}

func translateExecutionSchedule(value string) string {
	parts := strings.Fields(strings.TrimSpace(value))
	if len(parts) == 0 {
		return ""
	}
	// TODO: Replace this adapter with structured schedule parsing and validation so CrateOS owns recurrence semantics instead of inheriting cron quirks.
	if len(parts) == 5 {
		parts = append([]string{"0"}, parts...)
	}
	if len(parts) != 6 {
		return ""
	}
	for _, part := range parts {
		if !isSupportedScheduleToken(part) {
			return ""
		}
	}
	weekday := normalizeWeekdayToken(parts[5])
	day := normalizeDayToken(parts[3])
	month := normalizeMonthToken(parts[4])
	if weekday == "" || day == "" || month == "" {
		return ""
	}
	return fmt.Sprintf("%s-%s-%s %s:%s:%s", weekday, month, day, parts[2], parts[1], parts[0])
}

func isSupportedScheduleToken(value string) bool {
	value = strings.TrimSpace(value)
	if value == "" {
		return false
	}
	for _, r := range value {
		switch {
		case r >= '0' && r <= '9':
		case r >= 'A' && r <= 'Z':
		case r >= 'a' && r <= 'z':
		case r == '*', r == ',', r == '/', r == '-':
		default:
			return false
		}
	}
	return true
}

func normalizeWeekdayToken(value string) string {
	value = strings.TrimSpace(strings.ToUpper(value))
	if value == "" {
		return ""
	}
	if value == "*" {
		return "*"
	}
	return strings.ReplaceAll(value, "7", "0")
}

func normalizeDayToken(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	if value == "?" {
		return "*"
	}
	return value
}

func normalizeMonthToken(value string) string {
	value = strings.TrimSpace(strings.ToUpper(value))
	if value == "" {
		return ""
	}
	if value == "?" {
		return "*"
	}
	return value
}
