package state

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/crateos/crateos/internal/config"
	"github.com/crateos/crateos/internal/modules"
	"github.com/crateos/crateos/internal/platform"
)

func writeManagedExecutionArtifacts(desired config.ServiceEntry, crate CrateState, hasMod bool) {
	if hasMod || crate.ExecutionAdapter != "systemd" || crate.PrimaryUnitPath == "" {
		return
	}
	serviceContent := renderManagedServiceUnit(desired, crate)
	if _, err := writeManagedArtifact(
		filepath.ToSlash(filepath.Join("services", desired.Name, "runtime", "rendered", "systemd", crate.PrimaryUnit)),
		crate.PrimaryUnitPath,
		serviceContent,
		"service",
		fmt.Sprintf("rendered managed execution unit %s", crate.PrimaryUnit),
	); err != nil {
		log.Printf("warning: render managed execution unit %s: %v", desired.Name, err)
	}
	if crate.ExecutionMode == "job" && crate.CompanionUnitPath != "" {
		timerContent := renderManagedTimerUnit(desired, crate)
		if _, err := writeManagedArtifact(
			filepath.ToSlash(filepath.Join("services", desired.Name, "runtime", "rendered", "systemd", crate.CompanionUnit)),
			crate.CompanionUnitPath,
			timerContent,
			"service",
			fmt.Sprintf("rendered managed timer unit %s", crate.CompanionUnit),
		); err != nil {
			log.Printf("warning: render managed timer unit %s: %v", desired.Name, err)
		}
	}
}

func renderManagedServiceUnit(desired config.ServiceEntry, crate CrateState) string {
	lines := []string{
		"# Generated by CrateOS.",
		"# Generated native service artifact managed by CrateOS.",
		"[Unit]",
		fmt.Sprintf("Description=CrateOS managed workload for %s", desired.Name),
		"After=network.target",
		"",
		"[Service]",
	}
	if crate.ExecutionMode == "job" {
		lines = append(lines, "Type=oneshot")
	} else {
		lines = append(lines, "Type=simple")
	}
	if crate.ActorUser != "" {
		lines = append(lines, "User="+crate.ActorUser)
	}
	if crate.ActorGroup != "" {
		lines = append(lines, "Group="+crate.ActorGroup)
	}
	if crate.WorkingDir != "" {
		lines = append(lines, "WorkingDirectory="+crate.WorkingDir)
	}
	if crate.ActorRuntimeDir != "" {
		lines = append(lines, "RuntimeDirectory="+filepath.Base(crate.ActorRuntimeDir))
		lines = append(lines, "RuntimeDirectoryPreserve=yes")
	}
	if crate.ActorStateDir != "" {
		lines = append(lines, "StateDirectory=crateos/"+desired.Name+"/"+filepath.Base(crate.ActorStateDir))
	}
	if crate.EnvironmentFile != "" {
		lines = append(lines, "EnvironmentFile=-"+crate.EnvironmentFile)
	}
	if crate.StartCommand != "" {
		lines = append(lines, "ExecStart=/bin/sh -lc "+quoteSystemdShell(crate.StartCommand))
	} else {
		lines = append(lines, "# ExecStart pending module binding or execution.start_cmd")
	}
	if crate.Timeout != "" && crate.Timeout != "0" {
		lines = append(lines, "RuntimeMaxSec="+crate.Timeout)
	}
	if crate.StopTimeout != "" {
		lines = append(lines, "TimeoutStopSec="+crate.StopTimeout)
	}
	if crate.KillSignal != "" {
		lines = append(lines, "KillSignal="+crate.KillSignal)
	}
	lines = append(lines,
		"# TODO: Add stronger systemd hardening once actor provisioning and ownership enforcement land end-to-end.",
		fmt.Sprintf("# Managed actor pending lifecycle provisioning: %s", valueOrDefault(crate.ActorName, "unassigned")),
		fmt.Sprintf("# Managed actor id: %s", valueOrDefault(crate.ActorID, "pending")),
		fmt.Sprintf("# Managed actor user/group: %s:%s", valueOrDefault(crate.ActorUser, "pending"), valueOrDefault(crate.ActorGroup, "pending")),
		fmt.Sprintf("# Managed actor home: %s", valueOrDefault(crate.ActorHome, "pending")),
		fmt.Sprintf("# Deploy source: %s", valueOrDefault(crate.DeploySource, "unspecified")),
		fmt.Sprintf("# Entry: %s", valueOrDefault(crate.Entry, "unspecified")),
		"",
		"[Install]",
		"WantedBy=multi-user.target",
		"",
	)
	return strings.Join(lines, "\n")
}

func renderManagedTimerUnit(desired config.ServiceEntry, crate CrateState) string {
	onCalendar := translateExecutionSchedule(crate.Schedule)
	lines := []string{
		"# Generated by CrateOS.",
		"# Generated native timer artifact managed by CrateOS.",
		"[Unit]",
		fmt.Sprintf("Description=CrateOS managed schedule for %s", desired.Name),
		"",
		"[Timer]",
		fmt.Sprintf("Unit=%s", crate.PrimaryUnit),
		"Persistent=true",
	}
	if onCalendar != "" {
		lines = append(lines, "OnCalendar="+onCalendar)
	} else {
		lines = append(lines, "# OnCalendar translation failed; timer activation remains blocked.")
	}
	lines = append(lines,
		fmt.Sprintf("# Source schedule: %s", valueOrDefault(crate.Schedule, "unspecified")),
		"",
		"[Install]",
		"WantedBy=timers.target",
		"",
	)
	return strings.Join(lines, "\n")
}

func quoteSystemdShell(command string) string {
	command = strings.ReplaceAll(command, "\\", "\\\\")
	command = strings.ReplaceAll(command, "\"", "\\\"")
	return "\"" + command + "\""
}

func valueOrDefault(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func writeExecutionPosture(desired config.ServiceEntry, crate CrateState) {
	runtimeDir := filepath.Join(platform.CratePath("services", desired.Name), "runtime")
	if err := os.MkdirAll(runtimeDir, 0755); err != nil {
		log.Printf("warning: create execution posture dir %s: %v", desired.Name, err)
		return
	}
	path := filepath.Join(runtimeDir, "execution-posture.json")
	payload := map[string]interface{}{
		"generated_at": actualTimestamp(),
		"name":         crate.Name,
		"runtime":      crate.Runtime,
		"adapter":      crate.ExecutionAdapter,
		"mode":         crate.ExecutionMode,
		"status":       crate.ExecutionStatus,
		"actor": map[string]string{
			"name":                    crate.ActorName,
			"type":                    crate.ActorType,
			"id":                      crate.ActorID,
			"user":                    crate.ActorUser,
			"group":                   crate.ActorGroup,
			"home":                    crate.ActorHome,
			"runtime_dir":             crate.ActorRuntimeDir,
			"state_dir":               crate.ActorStateDir,
			"provisioning":            crate.ActorProvisioning,
			"provisioning_error":      crate.ActorProvisioningError,
			"provisioning_updated_at": crate.ActorProvisioningUpdatedAt,
			"provisioning_state_path": crate.ActorProvisioningStatePath,
			"ownership_status":        crate.ActorOwnershipStatus,
			"ownership_updated_at":    crate.ActorOwnershipUpdatedAt,
			"ownership_retired_at":    crate.ActorOwnershipRetiredAt,
		},
		"deploy": map[string]string{
			"source":           crate.DeploySource,
			"upload_path":      crate.UploadPath,
			"working_dir":      crate.WorkingDir,
			"entry":            crate.Entry,
			"install_command":  crate.InstallCommand,
			"environment_file": crate.EnvironmentFile,
		},
		"runtime_objects": map[string]string{
			"primary_unit":        crate.PrimaryUnit,
			"companion_unit":      crate.CompanionUnit,
			"primary_unit_path":   crate.PrimaryUnitPath,
			"companion_unit_path": crate.CompanionUnitPath,
		},
		"execution": map[string]string{
			"start_command":      crate.StartCommand,
			"schedule":           crate.Schedule,
			"timeout":            crate.Timeout,
			"stop_timeout":       crate.StopTimeout,
			"on_timeout":         crate.OnTimeout,
			"kill_signal":        crate.KillSignal,
			"concurrency_policy": crate.ConcurrencyPolicy,
			"summary":            crate.ExecutionSummary,
		},
		"note": "CrateOS is rendering intended execution posture here before full actor lifecycle enforcement, deploy materialization, and stronger execution policy enforcement land.",
	}
	data, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		log.Printf("warning: marshal execution posture %s: %v", desired.Name, err)
		return
	}
	if err := os.WriteFile(path, append(data, '\n'), 0644); err != nil {
		log.Printf("warning: write execution posture %s: %v", desired.Name, err)
	}
}

func inferExecutionArtifactPaths(desired config.ServiceEntry, crate CrateState, hasMod bool) (string, string) {
	if hasMod || crate.ExecutionAdapter != "systemd" || crate.PrimaryUnit == "" {
		return "", ""
	}
	renderedDir := filepath.Join(platform.CratePath("services", desired.Name), "runtime", "rendered", "systemd")
	primaryPath := filepath.Join(renderedDir, crate.PrimaryUnit)
	companionPath := ""
	if crate.CompanionUnit != "" {
		companionPath = filepath.Join(renderedDir, crate.CompanionUnit)
	}
	return primaryPath, companionPath
}

func managedExecutionUnitBase(name string) string {
	name = strings.ToLower(strings.TrimSpace(name))
	if name == "" {
		return "crateos-managed"
	}
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '-' || r == '_':
			b.WriteRune(r)
		default:
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		out = "managed"
	}
	return "crateos-" + out
}

func applyManagedExecutionNativeState(desired config.ServiceEntry, crate CrateState, hasMod bool) {
	if runtime.GOOS != "linux" || hasMod || crate.ExecutionAdapter != "systemd" {
		return
	}
	_, _, _ = syncManagedExecutionNativeUnits(desired, crate)
}

func syncManagedExecutionNativeUnits(desired config.ServiceEntry, crate CrateState) ([]Action, bool, []string) {
	actions := []Action{}
	reloaded := false
	issues := []string{}
	provisionActions, provisionIssues := prepareHostedManagedActor(desired, crate)
	actions = append(actions, provisionActions...)
	if len(provisionIssues) > 0 {
		issues = append(issues, provisionIssues...)
		return actions, reloaded, issues
	}
	primaryNativePath := managedNativeUnitPath(crate.PrimaryUnit)
	if crate.PrimaryUnitPath != "" && primaryNativePath != "" {
		if action, err := syncManagedArtifact(filepath.ToSlash(filepath.Join("native/services", desired.Name, crate.PrimaryUnit)), crate.PrimaryUnitPath, primaryNativePath, "service", fmt.Sprintf("installed hosted workload unit %s", crate.PrimaryUnit)); err != nil {
			issues = append(issues, err.Error())
		} else if action != nil {
			actions = append(actions, *action)
			reloaded = true
		}
	}
	companionNativePath := managedNativeUnitPath(crate.CompanionUnit)
	if crate.CompanionUnitPath != "" && companionNativePath != "" {
		if action, err := syncManagedArtifact(filepath.ToSlash(filepath.Join("native/services", desired.Name, crate.CompanionUnit)), crate.CompanionUnitPath, companionNativePath, "service", fmt.Sprintf("installed hosted workload timer %s", crate.CompanionUnit)); err != nil {
			issues = append(issues, err.Error())
		} else if action != nil {
			actions = append(actions, *action)
			reloaded = true
		}
	}
	if !desired.Enabled {
		if action, err := removeManagedArtifact(filepath.ToSlash(filepath.Join("native/services", desired.Name, crate.PrimaryUnit)), primaryNativePath, "service", fmt.Sprintf("removed hosted workload unit %s", crate.PrimaryUnit)); err != nil {
			issues = append(issues, err.Error())
		} else if action != nil {
			actions = append(actions, *action)
			reloaded = true
		}
		if companionNativePath != "" {
			if action, err := removeManagedArtifact(filepath.ToSlash(filepath.Join("native/services", desired.Name, crate.CompanionUnit)), companionNativePath, "service", fmt.Sprintf("removed hosted workload timer %s", crate.CompanionUnit)); err != nil {
				issues = append(issues, err.Error())
			} else if action != nil {
				actions = append(actions, *action)
				reloaded = true
			}
		}
	}
	return actions, reloaded, issues
}

func managedNativeUnitPath(unit string) string {
	unit = strings.TrimSpace(unit)
	if unit == "" {
		return ""
	}
	return filepath.Join("/etc/systemd/system", unit)
}

func activateHostedManagedWorkloads(cfg *config.Config, actual *ActualState, mods map[string]modules.Module) []Action {
	if runtime.GOOS != "linux" {
		return nil
	}
	var actions []Action
	var reloadNeeded bool
	actualByName := make(map[string]ServiceState, len(actual.Services))
	for _, svc := range actual.Services {
		actualByName[svc.Name] = svc
	}
	for _, desired := range cfg.Services.Services {
		mod, hasMod := mods[desired.Name]
		if hasMod {
			continue
		}
		crate := buildCrateState(desired, actualByName, mod, hasMod)
		syncActions, reloaded, issues := syncManagedExecutionNativeUnits(desired, crate)
		actions = append(actions, syncActions...)
		if len(issues) > 0 {
			continue
		}
		if reloaded {
			reloadNeeded = true
		}
	}
	if reloadNeeded {
		if err := systemctl("daemon-reload"); err == nil {
			actions = append(actions, Action{Description: "reloaded systemd after hosted workload unit changes", Component: "service", Target: "systemd"})
		}
	}
	for _, desired := range cfg.Services.Services {
		mod, hasMod := mods[desired.Name]
		if hasMod || !desired.Enabled {
			continue
		}
		crate := buildCrateState(desired, actualByName, mod, hasMod)
		actions = append(actions, activateHostedManagedUnits(desired, crate, actualByName)...)
	}
	return actions
}

func activateHostedManagedUnits(desired config.ServiceEntry, crate CrateState, actualByName map[string]ServiceState) []Action {
	var actions []Action
	switch crate.ExecutionMode {
	case "job":
		timerName := crate.CompanionUnit
		if timerName == "" || translateExecutionSchedule(crate.Schedule) == "" {
			return actions
		}
		if _, issues := prepareHostedManagedActor(desired, crate); len(issues) > 0 {
			return actions
		}
		timerState := actualByName[timerName]
		if !timerState.Enabled {
			if err := systemctl("enable", timerName); err == nil {
				actions = append(actions, Action{Description: fmt.Sprintf("enabled hosted workload timer %s for %s", timerName, desired.Name), Component: "service", Target: timerName})
			}
		}
		if !timerState.Active {
			if err := systemctl("start", timerName); err == nil {
				actions = append(actions, Action{Description: fmt.Sprintf("started hosted workload timer %s for %s", timerName, desired.Name), Component: "service", Target: timerName})
			}
		}
	default:
		serviceName := crate.PrimaryUnit
		if serviceName == "" {
			return actions
		}
		if _, issues := prepareHostedManagedActor(desired, crate); len(issues) > 0 {
			return actions
		}
		serviceState := actualByName[serviceName]
		if !serviceState.Enabled {
			if err := systemctl("enable", serviceName); err == nil {
				actions = append(actions, Action{Description: fmt.Sprintf("enabled hosted workload service %s for %s", serviceName, desired.Name), Component: "service", Target: serviceName})
			}
		}
		if desired.Autostart && !serviceState.Active {
			if err := systemctl("start", serviceName); err == nil {
				actions = append(actions, Action{Description: fmt.Sprintf("started hosted workload service %s for %s", serviceName, desired.Name), Component: "service", Target: serviceName})
			}
		}
	}
	return actions
}

func translateExecutionSchedule(value string) string {
	parts := strings.Fields(strings.TrimSpace(value))
	if len(parts) == 0 {
		return ""
	}
	if len(parts) == 5 {
		parts = append([]string{"0"}, parts...)
	}
	if len(parts) != 6 {
		return ""
	}
	for _, part := range parts {
		if !isSupportedScheduleToken(part) {
			return ""
		}
	}
	weekday := normalizeWeekdayToken(parts[5])
	day := normalizeDayToken(parts[3])
	month := normalizeMonthToken(parts[4])
	if weekday == "" || day == "" || month == "" {
		return ""
	}
	return fmt.Sprintf("%s-%s-%s %s:%s:%s", weekday, month, day, parts[2], parts[1], parts[0])
}

func isSupportedScheduleToken(value string) bool {
	value = strings.TrimSpace(value)
	if value == "" {
		return false
	}
	for _, r := range value {
		switch {
		case r >= '0' && r <= '9':
		case r >= 'A' && r <= 'Z':
		case r >= 'a' && r <= 'z':
		case r == '*', r == ',', r == '/', r == '-':
		default:
			return false
		}
	}
	return true
}

func normalizeWeekdayToken(value string) string {
	value = strings.TrimSpace(strings.ToUpper(value))
	if value == "" {
		return ""
	}
	if value == "*" {
		return "*"
	}
	return strings.ReplaceAll(value, "7", "0")
}

func normalizeDayToken(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	if value == "?" {
		return "*"
	}
	return value
}

func normalizeMonthToken(value string) string {
	value = strings.TrimSpace(strings.ToUpper(value))
	if value == "" {
		return ""
	}
	if value == "?" {
		return "*"
	}
	return value
}
