package state

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/crateos/crateos/internal/platform"
)

func writeManagedArtifact(logicalName, path, content, component, description string) (*Action, error) {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		log.Printf("warning: ensure managed artifact dir %s: %v", path, err)
		return nil, fmt.Errorf("ensure managed artifact dir %s: %w", path, err)
	}

	current, err := os.ReadFile(path)
	if err == nil && string(current) == content {
		return nil, nil
	}

	if err := snapshotManagedFile(logicalName, path); err != nil {
		log.Printf("warning: snapshot %s: %v", logicalName, err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		log.Printf("warning: write managed artifact %s: %v", path, err)
		return nil, fmt.Errorf("write managed artifact %s: %w", path, err)
	}

	return &Action{
		Description: description,
		Component:   component,
		Target:      path,
	}, nil
}

func snapshotManagedFile(logicalName, sourcePath string) error {
	data, err := os.ReadFile(sourcePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	snapshotPath := platform.CratePath("state", "last-good", filepath.FromSlash(logicalName))
	if err := os.MkdirAll(filepath.Dir(snapshotPath), 0755); err != nil {
		return err
	}

	metadataPath := snapshotPath + ".meta.json"
	meta := map[string]string{
		"logical_name": logicalName,
		"source_path":  sourcePath,
		"saved_at":     time.Now().UTC().Format(time.RFC3339),
	}
	if encoded, err := json.MarshalIndent(meta, "", "  "); err == nil {
		_ = os.WriteFile(metadataPath, append(encoded, '\n'), 0644)
	}

	return os.WriteFile(snapshotPath, data, 0644)
}

func syncManagedArtifact(logicalName, sourcePath, targetPath, component, description string) (*Action, error) {
	data, err := os.ReadFile(sourcePath)
	if err != nil {
		log.Printf("warning: read managed source %s: %v", sourcePath, err)
		return nil, fmt.Errorf("read managed source %s: %w", sourcePath, err)
	}
	if err := os.MkdirAll(filepath.Dir(targetPath), 0755); err != nil {
		log.Printf("warning: ensure native target dir %s: %v", targetPath, err)
		return nil, fmt.Errorf("ensure native target dir %s: %w", targetPath, err)
	}
	if current, err := os.ReadFile(targetPath); err == nil && string(current) == string(data) {
		return nil, nil
	}
	if err := snapshotManagedFile(logicalName, targetPath); err != nil {
		log.Printf("warning: snapshot native target %s: %v", targetPath, err)
	}
	mode := os.FileMode(0644)
	if strings.HasSuffix(strings.ToLower(targetPath), ".nmconnection") {
		mode = 0600
	}
	if err := os.WriteFile(targetPath, data, mode); err != nil {
		log.Printf("warning: write native target %s: %v", targetPath, err)
		return nil, fmt.Errorf("write native target %s: %w", targetPath, err)
	}
	return &Action{
		Description: description,
		Component:   component,
		Target:      targetPath,
	}, nil
}

func removeManagedArtifact(logicalName, targetPath, component, description string) (*Action, error) {
	if _, err := os.Stat(targetPath); err != nil {
		return nil, nil
	}
	if err := snapshotManagedFile(logicalName, targetPath); err != nil {
		log.Printf("warning: snapshot native target %s: %v", targetPath, err)
	}
	if err := os.Remove(targetPath); err != nil {
		log.Printf("warning: remove native target %s: %v", targetPath, err)
		return nil, fmt.Errorf("remove native target %s: %w", targetPath, err)
	}
	return &Action{
		Description: description,
		Component:   component,
		Target:      targetPath,
	}, nil
}

func isCrateManagedArtifact(data []byte) bool {
	return strings.HasPrefix(string(data), "# Generated by CrateOS. Do not edit manually.")
}
