package api

type serviceView struct {
	Name                       string     `json:"name"`
	DisplayName                string     `json:"display_name"`
	Category                   string     `json:"category,omitempty"`
	Description                string     `json:"description,omitempty"`
	Runtime                    string     `json:"runtime"`
	InstallMode                string     `json:"install_mode,omitempty"`
	ActorName                  string     `json:"actor_name,omitempty"`
	ActorType                  string     `json:"actor_type,omitempty"`
	ActorID                    string     `json:"actor_id,omitempty"`
	ActorUser                  string     `json:"actor_user,omitempty"`
	ActorGroup                 string     `json:"actor_group,omitempty"`
	ActorHome                  string     `json:"actor_home,omitempty"`
	ActorRuntimeDir            string     `json:"actor_runtime_dir,omitempty"`
	ActorStateDir              string     `json:"actor_state_dir,omitempty"`
	ActorProvisioning          string     `json:"actor_provisioning,omitempty"`
	ActorProvisioningError     string     `json:"actor_provisioning_error,omitempty"`
	ActorProvisioningUpdatedAt string     `json:"actor_provisioning_updated_at,omitempty"`
	ActorProvisioningStatePath string     `json:"actor_provisioning_state_path,omitempty"`
	ActorOwnershipStatus       string     `json:"actor_ownership_status,omitempty"`
	ActorOwnershipUpdatedAt    string     `json:"actor_ownership_updated_at,omitempty"`
	ActorOwnershipRetiredAt    string     `json:"actor_ownership_retired_at,omitempty"`
	DeploySource               string     `json:"deploy_source,omitempty"`
	UploadPath                 string     `json:"upload_path,omitempty"`
	WorkingDir                 string     `json:"working_dir,omitempty"`
	Entry                      string     `json:"entry,omitempty"`
	InstallCommand             string     `json:"install_command,omitempty"`
	EnvironmentFile            string     `json:"environment_file,omitempty"`
	ExecutionMode              string     `json:"execution_mode,omitempty"`
	ExecutionAdapter           string     `json:"execution_adapter,omitempty"`
	ExecutionStatus            string     `json:"execution_status,omitempty"`
	PrimaryUnit                string     `json:"primary_unit,omitempty"`
	CompanionUnit              string     `json:"companion_unit,omitempty"`
	PrimaryUnitPath            string     `json:"primary_unit_path,omitempty"`
	CompanionUnitPath          string     `json:"companion_unit_path,omitempty"`
	ExecutionStatePath         string     `json:"execution_state_path,omitempty"`
	StartCommand               string     `json:"start_command,omitempty"`
	Schedule                   string     `json:"schedule,omitempty"`
	Timeout                    string     `json:"timeout,omitempty"`
	StopTimeout                string     `json:"stop_timeout,omitempty"`
	OnTimeout                  string     `json:"on_timeout,omitempty"`
	KillSignal                 string     `json:"kill_signal,omitempty"`
	ConcurrencyPolicy          string     `json:"concurrency_policy,omitempty"`
	ExecutionSummary           string     `json:"execution_summary,omitempty"`
	Stateful                   bool       `json:"stateful,omitempty"`
	DataPath                   string     `json:"data_path,omitempty"`
	NativeDataPath             string     `json:"native_data_path,omitempty"`
	StorageSummary             string     `json:"storage_summary,omitempty"`
	Desired                    bool       `json:"desired"`
	Autostart                  bool       `json:"autostart"`
	Active                     bool       `json:"active"`
	Enabled                    bool       `json:"enabled"`
	Status                     string     `json:"status"`
	Health                     string     `json:"health"`
	Module                     bool       `json:"module"`
	Ready                      bool       `json:"ready"`
	PackagesInstalled          bool       `json:"packages_installed"`
	MissingPackages            []string   `json:"missing_packages,omitempty"`
	Summary                    string     `json:"summary,omitempty"`
	LastError                  string     `json:"last_error,omitempty"`
	LastAction                 string     `json:"last_action,omitempty"`
	LastActionAt               string     `json:"last_action_at,omitempty"`
	SuggestedRepair            string     `json:"suggested_repair,omitempty"`
	LastGoodStatus             string     `json:"last_good_status,omitempty"`
	LastGoodHealth             string     `json:"last_good_health,omitempty"`
	LastGoodAt                 string     `json:"last_good_at,omitempty"`
	LastGoodSummary            string     `json:"last_good_summary,omitempty"`
	Units                      []unitView `json:"units,omitempty"`
	Packages                   []string   `json:"packages,omitempty"`
}

type unitView struct {
	Name    string `json:"name"`
	Active  bool   `json:"active"`
	Enabled bool   `json:"enabled"`
	Status  string `json:"status"`
	Health  string `json:"health"`
}
